### ISSUE TITLE
Search Returns

### ISSUE THREAD

**Issue by geekrepublic** [Netflix/Scumblr#105]
Hello everyone.

I have spent most of the morning today configuring Facebook, Twitter, Google Search and when I run a search I get 0 returns. 

I am searching for stuff I know that will hit. Example for like Facebook

Name: Facebook
Query: Anonymous
Group: Group 1
Enabled: Check
Provider: Facebook Search
Tags: Facebook
Description: Facebook Search

When I try to run this I let it sit for a long time. I check back and 0 returns. 

Any idea what I can be doing wrong. Even after I setup the stuff with all the API and tokens I restarted the box.

![test](https://cloud.githubusercontent.com/assets/7629893/18014050/c65d4e18-6b86-11e6-9279-01e78416bd5c.PNG)
 Here is a  picture of what the stuff looks like.

**Comment by ahoernecke** [comment]
Hard to say with some additional info. Can you post the logs run your searches and post logs from sidekiq?

**Comment by sbehrens** [comment]
Closed due to 2.0 Scumblr release, if this is still needed please reopen this ticket or hop in the Scumblr Gitter chat room.
