### ISSUE TITLE
Initial setup with v2: ERROR:  relation "sessions" does not exist

### ISSUE THREAD

**Issue by juju4** [Netflix/Scumblr#108]
Hello,

I worked on an Ansible Role for scumblr and did an update for just released v2.
https://github.com/juju4/ansible-scumblr

setup is mostly the same than v1 but resulting instance doesn't pass test

```
$ curl -sSq http://localhost:3000/
PG::UndefinedTable at /unauthenticated
======================================

> ERROR:  relation "sessions" does not exist
LINE 5:                WHERE a.attrelid = '"sessions"'::regclass
                                          ^


activerecord (4.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb, line 592
------------------------------------------------------------------------------------------

ruby
  587             result.clear
  588             ret
  589           end
  590
  591           def exec_no_cache(sql, name, binds)
> 592             log(sql, name, binds) { @connection.async_exec(sql, []) }
  593           end

```

I don't see any new steps on the wiki and database is initialize by rake, so not sure why there is a relation missing.

Thanks

**Comment by ahoernecke** [comment]
Hi @juju4,

It looks like you're missing a database table that should be created in setup. I think this is our fault as there were some updates to the documentation that it looks like weren't pushed up. We'll get that pushed up this morning and we'll point you in the right direction on this ticket once it's there. 

Sorry about that!

**Comment by ahoernecke** [comment]
Wiki should be updated now. Take a look here: https://github.com/Netflix/Scumblr/wiki/Setting-up-Scumblr-2.0-%28New-install%29 

For instructions on setting up a fresh install. If you're interested in migrating from an earlier version there are instructions for that here:

https://github.com/Netflix/Scumblr/wiki/Upgrading-To-Scumblr-2.0-From-Scumblr-1.X

**Comment by sbehrens** [comment]
HI @juju4,

We missed pushing up our new Wiki documentation.  It should be up to date, specifically setting up 2.0 can be found here: https://github.com/Netflix/Scumblr/wiki/Setting-up-Scumblr-2.0-%28New-install%29.  We also have migration steps from 1.0 which you can see in the Wiki as well.

Thanks,

Scott
