### ISSUE TITLE
Facebook Search Deprecation

### ISSUE THREAD

**Issue by digital4rensics** [Netflix/Scumblr#11]
After configuring the Facebook credentials, I've received an error in the sidekiq logs regarding the search being executed.

ERROR: type: OAuthException, code: 11, message: (11) Post search has been deprecated [HTTP 400]

It appears this search is no longer valid for any new applications:
http://stackoverflow.com/questions/23511485/search-from-facebook-api/23523197#23523197

There are two proposed workarounds in the above post, but it seems even these may only work until some time next year.

Edit:
Be aware about this : "APIs are supported for at least two years after they're introduced, except for v1.0, which will only be available for one year after the release of v2.0." - Likely only available until April 30, 2015

**Comment by fenicks** [comment]
Just send a pull request for this issue: https://github.com/Netflix/Scumblr/pull/69.

**Comment by ahoernecke** [comment]
This fix has been merged. Thanks!
