### ISSUE TITLE
Scumblr v2 installation incorrect wiki on postgresql

### ISSUE THREAD

**Issue by juju4** [Netflix/Scumblr#111]
The wiki settings are presented for trusty but spoke about postgres 9.5. And it is only available on xenial+
https://github.com/Netflix/Scumblr/wiki/Setting-up-Scumblr-2.0-%28New-install%29
http://packages.ubuntu.com/search?keywords=postgresql-9.5&searchon=names&suite=all&section=all
no backports listed.
trusty only has 9.3 and it seems schema is not compatible. centos7 has 9.2.

Upgrade page mentions 9.4+ requirements but says it's valid on trusty which is not with upstream packages.
For packages, I suppose main alternative would be
https://yum.postgresql.org/repopackages.php
https://wiki.postgresql.org/wiki/Apt

**Comment by ahoernecke** [comment]
Hi @juju4,

The instructions on the wiki include steps to import the postgres repository which should allow installing postgres 9.4/9.5

```
sudo sh -c "echo 'deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' > /etc/apt/sources.list.d/pgdg.list"
wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get install postgresql-common
sudo apt-get install postgresql-9.5 libpq-dev
```

These steps seem to be working for us. What is happening when you follow these instructions?

**Comment by juju4** [comment]
Sorry. missed it. Too much quick read and didn't see repo was pointing to postgresql.org
