### ISSUE TITLE
Missing curl task on fresh install

### ISSUE THREAD

**Issue by ericalexanderorg** [Netflix/Scumblr#120]
Do I have to enable in a config option? I see legacy search options but no Curl Analyzer

![image](https://cloud.githubusercontent.com/assets/23297161/20116148/68f3033c-a5b8-11e6-80dc-b3fd82bca532.png)

**Comment by ahoernecke** [comment]
Curl should be further down in that list. If you type "curl" into the box it should filter down to it. Can you send a list of everything you see in that list if you scroll through it?

Thanks

**Comment by ericalexanderorg** [comment]
Face palm. Didn't see the scroll bar. Thx.

**Comment by ahoernecke** [comment]
No problem!
