### ISSUE TITLE
No results from Google

### ISSUE THREAD

**Issue by zeragual** [Netflix/Scumblr#122]
[7] pry(main)> SearchProvider::Google.new("scumblr").run
NoMethodError: undefined method `metadata' for nil:NilClass
from /home/ubuntu/Scumblr/lib/search_providers/provider.rb:43:in `initialize'

**Comment by sbehrens** [comment]
Hi @zeragual I'm taking a look.

**Comment by sbehrens** [comment]
Bug is in provider.rb, no objects are being inherited (exp. @options is nil if you print that out in the create_event method).  Confirmed @options is not-nil in base.rb if printed out in create_event method.   @ahoernecke

**Comment by sbehrens** [comment]
@zeragual Can you pull master and try again?  I have fixed the issue.  Please re-open this ticket if you are still having issues after updating.  

Also, I think your execution `SearchProvider::Google.new("scumblr").run` may result in some unexpected behaviors.  After you define a Google search provider, you can test via the command line by running the following 

`Task.last.perform_task`
