### ISSUE TITLE
rake db:structure:load errors

### ISSUE THREAD

**Issue by espressobeanie** [Netflix/Scumblr#127]
Hi,

I ran through all the previous steps flawlessly, but when I get to 'rake db:structure:load', I get this:

psql:/home/<user>/Scumblr/db/structure.sql:9: ERROR:  unrecognized configuration parameter "lock_timeout"
psql:/home/<user>/Scumblr/db/structure.sql:14: ERROR:  unrecognized configuration parameter "row_security"
psql:/home/<user>/Scumblr/db/structure.sql:270: ERROR:  type "jsonb" does not exist
LINE 12:     metadata jsonb,
                      ^
psql:/home/<user>/Scumblr/db/structure.sql:289: ERROR:  relation "results" does not exist
psql:/home/<user>/Scumblr/db/structure.sql:481: ERROR:  type "jsonb" does not exist
LINE 6:     metadata jsonb
                     ^
psql:/home/<user>/Scumblr/db/structure.sql:500: ERROR:  relation "system_metadata" does not exist
psql:/home/<user>/Scumblr/db/structure.sql:617: ERROR:  type "jsonb" does not exist
LINE 12:     metadata jsonb
                      ^
psql:/home/<user>/Scumblr/db/structure.sql:636: ERROR:  relation "tasks" does not exist
psql:/home/<user>/Scumblr/db/structure.sql:694: ERROR:  type "jsonb" does not exist
LINE 19:     metadata jsonb
                      ^
psql:/home/<user>/Scumblr/db/structure.sql:713: ERROR:  relation "users" does not exist
psql:/home/<user>/Scumblr/db/structure.sql:957: ERROR:  relation "results" does not exist
psql:/home/<user>/Scumblr/db/structure.sql:999: ERROR:  relation "system_metadata" does not exist
psql:/home/<user>/Scumblr/db/structure.sql:1027: ERROR:  relation "tasks" does not exist
psql:/home/<user>/Scumblr/db/structure.sql:1041: ERROR:  relation "users" does not exist
psql:/home/<user>/Scumblr/db/structure.sql:1139: ERROR:  relation "results" does not exist
psql:/home/<user>/Scumblr/db/structure.sql:1163: ERROR:  relation "tasks" does not exist
psql:/home/<user>/Scumblr/db/structure.sql:1203: ERROR:  relation "system_metadata" does not exist
psql:/home/<user>/Scumblr/db/structure.sql:1236: ERROR:  relation "users" does not exist
psql:/home/<user>/Scumblr/db/structure.sql:1354: ERROR:  relation "results" does not exist
psql:/home/<user>/Scumblr/db/structure.sql:1424: ERROR:  relation "users" does not exist
psql:/home/<user>/Scumblr/db/structure.sql:1466: ERROR:  relation "results" does not exist

**Comment by sbasgall** [comment]
The "lock_timeout" parameter wasn't added until postgres 9.3.
Are you using a new enough version?

**Comment by ahoernecke** [comment]
Hi @espressobeanie, were you able to get this working?

**Comment by ahoernecke** [comment]
Based on other comments/issues you've created I think you have this resolve. I'm going to close the issue but please reopen if you are still having problems.
