### ISSUE TITLE
How to implement some tasks for a specified results?

### ISSUE THREAD

**Issue by dleyanlin** [Netflix/Scumblr#134]
how to do for assign task for a special result?

example:
  
  I create three results, i only want to implement curl task for second result. how to do?

thanks

**Comment by ahoernecke** [comment]
Hi @dleyanlin, what you'd want to do is create a saved filter with the result(s) you want in scope for the task. (Instructions here: https://github.com/Netflix/Scumblr/wiki/Create-Your-First-Result-Filter) 

Then from the curl task config you should be able to select the filter for the "Results Filter" option, save the task, and then it will only run on the result(s) matching the filter.

Feel free to drop by our gitter channel if you have any other questions: https://gitter.im/Netflix/Scumblr
