### ISSUE TITLE
Issue creating new Scumblr task search

### ISSUE THREAD

**Issue by geometric-networks** [Netflix/Scumblr#135]
Hi,

I have an issue where after tying my API keys for Google, Facebook, eBay, etc... I continue to get access denied or error messages when attempting to create new tasks that search these services. I checked the permissions for scumblr.rb and they don't appear to be different from the other files. I'm not sure how to troubleshoot further. Any suggestions?

Thanks in advance

**Comment by ahoernecke** [comment]
Hi, can you be more specific on the error messages your receiving and from where? If you could post screenshots of the errors your getting it might be useful.

**Comment by geometric-networks** [comment]
Yep, screenshots are attached. In Scumblr WebUI, under TASKS, New Task, essentially all the API keys I defined in /home/<usr>/Scumblr/environments/initializer/scumblr.rb are not working.

![twitter](https://cloud.githubusercontent.com/assets/10804971/21154527/abda49ae-c13c-11e6-82a9-5aa00fb24dcf.PNG)
![google](https://cloud.githubusercontent.com/assets/10804971/21154528/abdec6b4-c13c-11e6-9352-c7f5bc6ea822.PNG)
![github](https://cloud.githubusercontent.com/assets/10804971/21154529/abe3ba48-c13c-11e6-8604-b4139f0cb08d.PNG)
![youtube](https://cloud.githubusercontent.com/assets/10804971/21154530/abe8a3aa-c13c-11e6-9a9b-4867978b55bd.PNG)
![ebay](https://cloud.githubusercontent.com/assets/10804971/21154531/abeb26d4-c13c-11e6-923d-83462277bf11.PNG)

**Comment by ahoernecke** [comment]
A few things,

1. I'm assuming you've restarted your server?
2. The path you posted for the scumblr.rb file is not correctly. The location should be `/home/Scumblr/config/initializers/scumblr.rb` Please make sure it's in the right place.
3. If fixing the above doesn't work can you please post a (redacted) screenshot of your scumblr.rb file?

Thanks

**Comment by geometric-networks** [comment]
Ahoernecke,

1. Yes. No luck.
2. So I would need a user named Scumblr or ensure the Scumblr folder is in the /home system directory itself and not inside a specific user folder?

Thanks

**Comment by ahoernecke** [comment]
Based on your original comment it appeared the scumblr root directory was /home/Scumblr... It doesn't really matter what this is, but where have you have the scumblr code there should be a /config/initializer folder. This is where the scumblr.rb file need to be. In other words:
```
<scumblr folder>/config/initializers/scumblr.rb
```

**Comment by geometric-networks** [comment]
ahoernecke,

apologies for misclarification. original path was /home/<usr>/Scumblr, but when I move to /home/Scumblr, I now see several new sections where I didn't before. That definitely helped! I don't understand the API error part. It's in the correct location: /home/Scumblr/config/initializers/scumblr.rb and the scumblr.rb.example file was taken out. File permissions are set to 0664.

**Comment by ahoernecke** [comment]
Can you post a redacted version of your scumblr file and a directory listing for the initializers folder?

**Comment by geometric-networks** [comment]
I did. Please see original thread: https://github.com/Netflix/Scumblr/issues/135

**Comment by ahoernecke** [comment]
Oh thanks, I missed it. I think I see what's happening here... The ENV["..."] syntax will load the value from an environment variable. So for example you have the google application set to ENV["Scumblr"]. This is going to check for an environment variable named "Scumblr" and set the value to that variable's value.

From looking at your config, I think what you've done is put the actual secret value in the quotes (i.e. ENV["secret here"]. This won't work because it will be looking for a environment variable with the secret's name.

If this is right you have two options:

1. Either change the config back to the same and then set the appropriate environment variables to the secret values

or 

2. If you'd rather put the secrets inline just change the config to be like this:
```
config.google_developer_key = "secret_here"
```
(In other works get rid of the ENV[] part)

**Comment by geometric-networks** [comment]
Np. Ah, I see I see. That makes sense. I completely overlooked something. Okay, I'll give that a try.

**Comment by geometric-networks** [comment]
I confirmed it works! Thank you. :)
