### ISSUE TITLE
Can Scumblr automatically run stored jobs?

### ISSUE THREAD

**Issue by espressobeanie** [Netflix/Scumblr#139]
Hi,

Is there a way for Scumblr to automatically run all stored jobs on a rotating schedule or cron job? I thought Workflowable would do this, but that component appears to be more conditional.

Thanks in advance,

**Comment by ahoernecke** [comment]
Hi @espressobeanie,

Yes scumblr can do this. There is a rake task available that you can setup to run as a cron job. This task will run all the tasks that you have created that are enabled.

```
rake run_tasks_and_email_updates
```

Note you you'll need to have your path/working directory setup properly so it can find the task, run the cron job under the right user, etc.

Please reopen if this doesn't answer your questions or if you need any other info.
