### ISSUE TITLE
Issue with updating Results Display Field

### ISSUE THREAD

**Issue by mars01** [Netflix/Scumblr#140]
Good afternoon, I'm seeing another issue crop up where I receive the following error after attempting to update the Results Display Field:

![image](https://cloud.githubusercontent.com/assets/22796280/21813378/0744038c-d724-11e6-943e-b830d1cd55b3.png)

I'm also seeing "No Results Found. (151 results filtered)" under my Results tab.

**Comment by ahoernecke** [comment]
Can you provide the logs you're seeing when you get this error?

**Comment by espressobeanie** [comment]
I'm not seeing any direct output with this error. I also checked the Scumblr log folder and the two files there didn't show much. When I run the [troubleshooting commands to retrieve results](https://github.com/Netflix/Scumblr/wiki/Troubleshooting), I'm getting the following:

 res = Result.where(id: <id>).first
SyntaxError: unexpected '<'
res = Result.where(id: <id>).first

res.metadata
NameError: undefined local variable or method `res' for main:Object

Does Scumblr have another debug mode?

**Comment by ahoernecke** [comment]
Hi,

There should almost certainly be something in the log if you're seeing this message. Try tailing the end of the production log while making a request that errors.

For the command you pasted above, you need to replace ```<id>``` with a number (i.e. the id number of a result). 

If you run scumblr in development mode (```RAILS_ENV=development rails s```) it will provide verbose errors when a problem something occurs.

**Comment by mars01** [comment]
I see. That worked and I'm able to see the id:, title:, url:, etc... outputs from the python CLI.

Okay, so on the filter settings, if I select "Is Closed?", it'll show all my previous results. All set. Thank you!

**Comment by ahoernecke** [comment]
Cool no problem!
