### ISSUE TITLE
Facebook search is not returning results

### ISSUE THREAD

**Issue by ITSCT** [Netflix/Scumblr#143]
Hi ,
I completed the configurations for scumblr, but when I try to perform a search using  `SearchProvider::Facebook.new("scumblr").run`  I dont get any results with this error `NoMethodError: undefined method `metadata' for nil:NilClass
from /home/ubuntu/Scumblr/lib/search_providers/provider.rb:43:in `initialize'`

**Comment by sbehrens** [comment]
Hi @ITSCT,

Which version of scumblr are you using?

**Comment by ITSCT** [comment]
Scumblr 2

**Comment by sbehrens** [comment]
Can you try invoking the search from the UI and sending me over any full stack traces found in the Events view?  (/events)

**Comment by ITSCT** [comment]
![capture](https://cloud.githubusercontent.com/assets/25432912/22462141/ba7cf0ee-e7b4-11e6-8918-1cae1518573d.PNG)

That's all what I found in the event view

**Comment by sbehrens** [comment]
It doesn't look like you run the task, can you navigate to the task page, select your facebook search and click Run?

**Comment by ITSCT** [comment]
![image](https://cloud.githubusercontent.com/assets/25432912/22476915/bcda720c-e7ec-11e6-88b0-2f1f04974d46.png)


![image](https://cloud.githubusercontent.com/assets/25432912/22476976/05f5f420-e7ed-11e6-8bfa-75fb53a71d08.png)

**Comment by sbehrens** [comment]
Could you click that Event ID `7` and paste the stack trace associated with the Event ID 7?

**Comment by ITSCT** [comment]
Id	7
Eventable	Task 1
Action	Error
User	
Source	Task: Test
Details	Unable to run task Test. Error: type: OAuthException, code: 1, message: Error validating client secret. [HTTP 400] ["/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/koala-1.10.0/lib/koala/oauth.rb:367:in `fetch_token_string'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/koala-1.10.0/lib/koala/oauth.rb:314:in `get_token_from_server'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/koala-1.10.0/lib/koala/oauth.rb:210:in `get_app_access_token_info'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/koala-1.10.0/lib/koala/oauth.rb:220:in `get_app_access_token'", "/home/ubuntu/Scumblr/lib/search_providers/facebook.rb:46:in `initialize'", "/home/ubuntu/Scumblr/app/models/task.rb:159:in `new'", "/home/ubuntu/Scumblr/app/models/task.rb:159:in `perform_task'", "/home/ubuntu/Scumblr/app/workers/task_worker.rb:30:in `perform'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:155:in `execute_job'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:136:in `block (3 levels) in process'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-status-0.6.0/lib/sidekiq-status/server_middleware.rb:37:in `call'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/server/active_record.rb:6:in `call'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/logging.rb:32:in `with_context'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/server/logging.rb:7:in `call'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:131:in `block (2 levels) in process'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:171:in `stats'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:130:in `block in process'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:122:in `process'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:81:in `process_one'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:69:in `run'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/util.rb:17:in `watchdog'", "/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/util.rb:25:in `block in safe_thread'"]

**Comment by ahoernecke** [comment]
Hi @ITSCT,

This appears to be an error from Facebook indicating your oauth credentials are not valid. Can you double check your configuration and make sure you're providing the right values, and that they are inputted correctly?

**Comment by sbehrens** [comment]
Hi @ITSCT,

Please re-open the issue if you are still seeing problems after updating your oauth credentials.  

_Scott
