### ISSUE TITLE
curl_analyzer will not run on FIPS enabled systems

### ISSUE THREAD

**Issue by woot4moo** [Netflix/Scumblr#144]
The `curl_analyzer` class  will not successfully run on a system that has FIPS only algorithms enabled.

```
if(previous_versions.present?)
      digest = Digest::MD5.file (full_file_path)
      previous_versions.each do |v|
        if(v.attachment.fingerprint != digest.to_s)
          previous_versions.delete(v)
          v.delete
        end
      end
    end
```

**Comment by ahoernecke** [comment]
Thanks @woot4moo, glad you're taking a look at the project. I suspect we can fix this. I'll do some investigation and update the issue.

**Comment by ahoernecke** [comment]
Just pushed a fix for this. It's in a branch now but should be merged sometime in the next few weeks.
