### ISSUE TITLE
Status update on Result view creates Postgres Error / Fails

### ISSUE THREAD

**Issue by matt7277** [Netflix/Scumblr#157]
Status assignments via the Action menu in the Index view for Results works as expected from what I can tell. Example: https://scumblr.example.com/results/ . Looking at about 60 results, select the checkboxes for results you want to update, set a particular status such as Investigating or Closed, click Update. Works just fine 

Status updates via the individual result view appears to fail. Example: https://scumblr.example.com/results/240 , Click on Investigating or Closed in the Top Status Change navbar creates an error that resembles the below:

`Error (4d19344b-05ae-4bbd-ad96-de13a0aa54f3): PG::DatatypeMismatch in ResultsController#update_status ERROR: argument of WHERE must be type boolean, not type integer LINE 1: SELECT "statuses".* FROM "statuses" WHERE (2) ORDER BY "st... ^ Full Trace: /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec' /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache' /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log' /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument' /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-
`

**Comment by ahoernecke** [comment]
Thanks @matt7277,

It looks like we introduced a bug on the update status action. Can you pull the latest code from master and try again?

Thanks,
Andy
