### ISSUE TITLE
"SYSTEM METADATA" menu results in error

### ISSUE THREAD

**Issue by mcpeak** [Netflix/Scumblr#162]
Clicking the "system metadata" top menu option yields an error page "We're sorry, but something went wrong".  This happens while I'm authenticated and is repeatable.

I'm a new user to the system so haven't done any profile customization or anything yet.  Aside from this I don't have context to add but am available to test potential fixes.

**Comment by ahoernecke** [comment]
Hi @mcpeak,

It looks like we added the menu item for all users even though non-admins don't have access. I'll push up a fix for this.

Thanks!

**Comment by ahoernecke** [comment]
Fix pushed. Thanks again!
