### ISSUE TITLE
hello# brother of good

### ISSUE THREAD

**Issue by glerinsonum** [Netflix/Scumblr#168]
@andrewachen @pablete @zkwentz @fabiokung @jkriss @devesh 
  I've spent time futile by tried for to find an application GUI for Windows, to extract informations via id or username of facebok, like as maltego. but maltego is very complication. i would like to buy this program 100$, but not cost 100$, but cost more.

Is there any thing for windows as the gift, to extract some informations from facebook, location, place, email. 

I buy. In 100$
Other I there no

How I Can Use This Product !!! 
Brother, there I can't see an video demonstration for to learning how is the use and implemention in those scripts that are programmed with python,ruby,perl. 

Make things easy brother.

**Comment by sbehrens** [comment]
Setup instructions for this application can be found: https://github.com/Netflix/Scumblr/wiki.  We do not support windows for this tool.
