### ISSUE TITLE
Installation Guide on Wiki - Formatting Errors

### ISSUE THREAD

**Issue by serrastusbear** [Netflix/Scumblr#175]
Appears that some changes to wiki guide for installation included some formatting errors in including codeblocks, etc. Instructions are now difficult to follow.

**Comment by sbehrens** [comment]
@serrastusbear Can you provide an example?

**Comment by serrastusbear** [comment]
Yes, attaching a screenshot. It looks like something is killing the preformatting/codeblock markup, or '```' are unbalanced somewhere and throwing off the rest of the guide on https://github.com/Netflix/Scumblr/wiki/Setting-up-Scumblr-2.0-%28New-install%29

![screenshot_2017-04-26_13-33-27](https://cloud.githubusercontent.com/assets/10403633/25453103/1a06e5a2-2a85-11e7-8ffa-09892765cab4.png)

**Comment by sbehrens** [comment]
Resolved.

it looks as though github now requires code blocks to not have any spaces before in the markdown file.  I went ahead and updated the entire wiki and all code blocks should be formatted correctly.
