### ISSUE TITLE
stucked at bundle exec sidekiq -l log/sidekiq.log &

### ISSUE THREAD

**Issue by berry2012** [Netflix/Scumblr#176]
Hi,

ubuntu@scumblr:~/Scumblr$ sudo bundle exec sidekiq -l log/sidekiq.log &
[2] 30780
ubuntu@scumblr:~/Scumblr$ bundler: command not found: sidekiq
Install missing gem executables with `bundle install`

[2]+  Exit 127                sudo bundle exec sidekiq -l log/sidekiq.log
ubuntu@scumblr:~/Scumblr$ sudo bundle install

I got this error while trying to bundle install
Installing active_model_serializers (0.10.2)
Gem::InstallError: active_model_serializers requires Ruby version >= 2.1.
An error occurred while installing active_model_serializers (0.10.2), and Bundler cannot continue.
Make sure that `gem install active_model_serializers -v '0.10.2'` succeeds before bundling.

**Comment by ahoernecke** [comment]
Hi @berry2012,

It looks like you potentially missed some instructions earlier on. Please make sure you have right ruby version installed and set as default (2.3.1). This will be required for the bundle install to complete properly. 

Thanks!
