### ISSUE TITLE
Email sending problem

### ISSUE THREAD

**Issue by Joukahainen123** [Netflix/Scumblr#177]
Hi, I have a fresh install of Scumblr2 (previously using version 1).

For some reason I cannot get the notification emails to function.
Running on Ubuntu 16.04, with local postfix installation (tested to work with manual sendin emails using telnet). My enviroment.rb (and other .rb files settings are as follows):

# mail settings
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.perform_deliveries = true
  config.action_mailer.default_url_options = { :host => 'my.hostname.here', :port => 3000, :protocol => 'http' }
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
  address:                 "my.hostname.here",
  port:                    25,
  enable_starttls_auto:    false
}

 Rails.application.routes.default_url_options[:host] = "my.ip.here:3000"
 Rails.application.routes.default_url_options[:protocol] = "http"

And I have created results filter and subscribed users to it. 

When I run rake send_email_updates (with fresh new results), I do not get emails (nothing shown in postfix logs, so it does not even try to send email).

rake send_email_updates --trace
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
** Invoke send_email_updates (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute send_email_updates

With these settings everything worked in previous version. What could be the problem here?

**Comment by ahoernecke** [comment]
Hi @Joukahainen123,

We just identified/fixed a bug in the email notifications. Can you pull the latest code from master and see if that resolves your problem. 

As a side note, this add a new configuration option in the scumblr.rb (email_source_address) which sets who the emails appear to come from. Not being able to set this value was causing some problems in AWS.

**Comment by Joukahainen123** [comment]
Hi,

Now working with latest 2.0.2 release. Thanks a lot. :)

**Comment by ahoernecke** [comment]
No problem!
