### ISSUE TITLE
Twitter Searching error

### ISSUE THREAD

**Issue by przem100** [Netflix/Scumblr#179]
Hi All,
I got 'Unable to run task Twitter vulnerability' error during twitter task running.
I have found trivial error in lib/search_providers/provider.rb
in line 113 there is: 
              ` @event_metadata[level] ||= []`
and should be:
               `@event_metadata[level] ||= {}`

After correction it works great

Please correct before next release

Regards

**Comment by sbehrens** [comment]
Hi @przem100,

Would you mind providing the error you are seeing.  Looking at the code block:

```ruby
      @event_metadata[level] ||= []
      @event_metadata[level] << event_details.id
```

That object should be an array, as we are using it to store `event_details.id`.  Using << to append to the array.  I'm not sure why making that a hash would work, you cannot append to a hash using the << operator.
