### ISSUE TITLE
SCUMBLR landing page taking too long to load

### ISSUE THREAD

**Issue by berry2012** [Netflix/Scumblr#180]
Hi All,
Is this project up to date?
I managed to deploy scumblr on my ubuntu.

 ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
 rails -v
Rails 4.2.6

Got this error when I did **rake**
 rake db:create
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.

I proceeded and from the Scumblr root folder:
redis-server &
bundle exec sidekiq -l log/sidekiq.log &
bundle exec rails s -b 0.0.0.0 &

The web page keeps loading and loading and takes so long without fully loading.

<img width="1269" alt="screen shot 2017-05-03 at 3 53 39 pm" src="https://cloud.githubusercontent.com/assets/10167641/25666560/c5658b86-3018-11e7-8b73-afab341b6fec.png">

![screen shot 2017-05-03 at 3 56 57 pm](https://cloud.githubusercontent.com/assets/10167641/25666699/2e9bd330-3019-11e7-9a3f-4ee20248f20a.png)

**Comment by sbehrens** [comment]
Hi @berry2012 ,

> [DEPRECATION] last_comment is deprecated. Please use last_description instead.
That's just a warning not an error.

Can you send us a screenshot of the developer console when the page isn't loading?  That may help us identify the issue.

**Comment by berry2012** [comment]
Hi @sbehrens 

I had to leave the system for about 1 hour and everything seems to be loading fine now.

![screen shot 2017-05-03 at 5 17 28 pm](https://cloud.githubusercontent.com/assets/10167641/25670439/994d3ea2-3024-11e7-8580-8e10070374d0.png)

I want to proceed with the documentations in creating tasks etc

Thanks

**Comment by sbehrens** [comment]
Are you still seeing this issue?
