### ISSUE TITLE
Results table doesn't exist.

### ISSUE THREAD

**Issue by sivadharma** [Netflix/Scumblr#183]
While running the tool on localhost, I'm getting an error as follows

PG::UndefinedTable - ERROR:  relation "results" does not exist
LINE 5:                WHERE a.attrelid = '"results"'::regclass

Please guide me to fix the above error.

Note: Previously I had the same error on "Session Table", I solved it by the query "rake db:migrate".

**Comment by ahoernecke** [comment]
Hi @sivadharma.  Please return to the wiki and ensure you've followed all the instructions to get your application setup. The missing database tables are likely a result of a missed or out of order step when performing the setup: https://github.com/Netflix/Scumblr/wiki/Setting-up-Scumblr-2.0-%28New-install%29

**Comment by sivadharma** [comment]
sure. i will get back to you soon.

**Comment by sivadharma** [comment]
Thank you so much for your reply, followed your instructions and sorted it out. Now, where can i find the manual to set up things after installation?

**Comment by sbehrens** [comment]
The Getting started section of the wiki will give you the basic concepts:

https://github.com/Netflix/Scumblr/wiki/Getting-Started

The wiki in general is your best spot for this sort of information.  If you have further questions, hop into our Gitter chatroom: https://gitter.im/Netflix/Scumblr?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by patulskitime** [comment]
@sivadharma  Do you remember what your fix was for this issue?
