### ISSUE TITLE
Google search fails

### ISSUE THREAD

**Issue by bofinbabu** [Netflix/Scumblr#193]
When I tried to do Google search specific to the domain pastebin.com as described in: https://mig5.net/content/monitoring-pastebincom-scumblr

I'm getting the following error:

Unable to run task Pastebin Crawler. Error: undefined method `[]' for nil:NilClass ["/home/b05/Scumblr/lib/search_providers/provider.rb:113:in `create_event'", "/home/b05/Scumblr/lib/search_providers/provider.rb:92:in `create_error'", "/home/b05/Scumblr/lib/search_providers/provider.rb:33:in `block in initialize'", "/home/b05/Scumblr/lib/search_providers/provider.rb:30:in `each'", "/home/b05/Scumblr/lib/search_providers/provider.rb:30:in `initialize'", "/home/b05/Scumblr/lib/search_providers/google.rb:73:in `initialize'", "/home/b05/Scumblr/app/models/task.rb:137:in `new'", "/home/b05/Scumblr/app/models/task.rb:137:in `perform_task'", "/home/b05/Scumblr/app/workers/task_worker.rb:30:in `perform'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:155:in `execute_job'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:136:in `block (3 levels) in process'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-status-0.6.0/lib/sidekiq-status/server_middleware.rb:37:in `call'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/server/active_record.rb:6:in `call'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/logging.rb:32:in `with_context'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/server/logging.rb:7:in `call'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:131:in `block (2 levels) in process'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:171:in `stats'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:130:in `block in process'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:122:in `process'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:81:in `process_one'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:69:in `run'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/util.rb:17:in `watchdog'", "/home/b05/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/util.rb:25:in `block in safe_thread'"]

I'm a first time user. Your help is very much appreciated.

**Comment by sbehrens** [comment]
Hi @bofinbabu,

Are you using the latest version of Scumblr?  That error was resolved a number of months ago.

**Comment by sbehrens** [comment]
Hi @bofinbabu,

I am closing this issue since I didn't hear back from you.  Please reopen if upgrading to the latest Scumblr didn't resolve the issue.
