### ISSUE TITLE
Ruby Install in rbenv - TMPDIR error

### ISSUE THREAD

**Issue by jberlynn** [Netflix/Scumblr#210]
On the ruby install with command 
> rbenv install 2.3.1 
produces the following error:
> ruby-build: TMPDIR=/tmp cannot hold executables (partition possibly mounted with `noexec`

**Comment by ahoernecke** [comment]
This would appear to be an issue with the rbenv installation being unable to use your tmp dir. Please see this issue on from the rbenv repo. https://github.com/rbenv/ruby-build/issues/703

It looks like you need to set the tmpdir environment variable to a suitable location.
