### ISSUE TITLE
Searches - Not Working

### ISSUE THREAD

**Issue by pappyc17** [Netflix/Scumblr#22]
Hello,

I am having trouble running a regular search using provided in the installation guide:

1.On the top menu click "Searches"
2.Click "New Search"
3.Give your search an identifiable name
4.Add a query string. We're going to use "netflix scumblr"
5.Select a Search Provider. We're going to use Google
6.If additional options are available, they will appear inline. We'll leave the additional options blank for now.
7.Add any tags you would like to be automatically applied to these results. We'll add one tag, "Scumblr"
8.If you'd like, add a verbose description to the search
9.When done click "Create Search"

I can create a search, but when I go to run it, nothing is happening says "Running Search" if I look at the task it says "No Jobs Running" which is clearly wrong..

![scumblr](https://cloud.githubusercontent.com/assets/7980563/4963268/e6ffaf40-6704-11e4-9ea9-3aac1785caf2.PNG)

**Comment by ahoernecke** [comment]
Hi @pappyc17, wondered if you were ever able to get this figured out.

**Comment by ahoernecke** [comment]
Assuming fixed.
