### ISSUE TITLE
Missing move_vulnerability_task or create_vulnerability_jira_task in app/views/results/metadata/_vulnerability.html.erb error

### ISSUE THREAD

**Issue by xntrik** [Netflix/Scumblr#221]
Hey Folks,

Running this 'out-of-the-box' with version 2.1.0 I'm noticing errors getting thrown when expanding the 'Vulnerabilities' accordion on the 'Results' page. 

The issues appear to be:
https://github.com/Netflix/Scumblr/blob/master/app/views/results/metadata/_vulnerability.html.erb#L37
and
https://github.com/Netflix/Scumblr/blob/master/app/views/results/metadata/_vulnerability.html.erb#L50

Both of those have an if check for whether move_vulnerability_task or create_vulnerability_jira_task is defined, which they are, unfortunately, they're nil.

**Comment by sbehrens** [comment]
Howdy, sorry Christian for the late reply.  We'll take a look at this one.

**Comment by sbehrens** [comment]
Fixed, `defined` is always set but we should have used `present` since that will only return if the object is not nil.
