### ISSUE TITLE
Pull RSS feed in environment with proxy configuration

### ISSUE THREAD

**Issue by ManoftheSea** [Netflix/Scumblr#230]
When I try to run an RSS search, I get an error about redirection.  Which makes sense, in my environment I need to use a proxy to get to the internet.  I tried the wiki configuration directions, but don't see how to set http_proxy/https_proxy for Scumblr. I'm on the suggested Ubuntu 14.04.

Could I trouble you to add a note?

**Comment by sbehrens** [comment]
Hi @ManoftheSea ,

Is the proxy for incoming connections to Scumblr or outgoing?

**Comment by ManoftheSea** [comment]
Outgoing.  It seems it should be as easy as setting http_proxy in environment, but I'm clearly doing something wrong. 

I have curl at the command-line working. Perhaps an option to bundle, or a config file somewhere?

On March 8, 2018 9:00:03 PM UTC, Scott Behrens <notifications@github.com> wrote:
>Hi @ManoftheSea ,
>
>Is the proxy for incoming connections to Scumblr or outgoing?  
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Netflix/Scumblr/issues/230#issuecomment-371622580

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sbehrens** [comment]
I think a global config option for proxy makes sense.  We maintain config files in the https://github.com/Netflix/Scumblr/blob/master/config/initializers/scumblr.rb.  You could consider adding the right proxy settings and then passing in that config option (if set or initialized) to the http request portion of the rss sync.   If you get that all working feel free to send a PR and we'll take a look.
