### ISSUE TITLE
How  To Use Email Notifications

### ISSUE THREAD

**Issue by hakkar** [Netflix/Scumblr#24]
I set the default URL options:
Rails.application.routes.default_url_options[:host] = "163.com"
Rails.application.routes.default_url_options[:protocol] = "http"

but I can not receive mail

**Comment by ahoernecke** [comment]
Hi @hakkar,

I think I may have forgotten to include some instructions on getting email notifications sent out. I added a section to the wiki: https://github.com/Netflix/Scumblr/wiki#email-notification

Let me know if that helps.
