### ISSUE TITLE
Run specific Task

### ISSUE THREAD

**Issue by G0zsilva** [Netflix/Scumblr#240]
Hello,

First of all, I'd like to thank you for the platform I'm really enjoying.

I would like to know if you have any command to execute a specific Task, either via Rake or API.

**Comment by sbehrens** [comment]
Hi @acassio22,

I have a way you can run a task via the CLI

**CLI**

```
# rails c
Task.find(<id>).perform_task
```

id can be your task id number (found when browsing the task via the UI).


For API you can try a POST request to `scumblr.your_env.com/tasks/<id>/run`.  That will run the task.

**Comment by G0zsilva** [comment]
Thanks!!!
