### ISSUE TITLE
Node.js 4.x LTS Argon is no longer actively supported

### ISSUE THREAD

**Issue by infracritical** [Netflix/Scumblr#244]
You may want to update your instructions...

===================

root# curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -

=======================================================================
=======================================================================

                              DEPRECATION WARNING                            

  Node.js 4.x LTS Argon is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_8.x — Node.js 8 LTS "Carbon" (recommended)
   * https://deb.nodesource.com/setup_10.x — Node.js 10 Current

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.

  The NodeSource Node.js distributions repository contains
  information both about supported versions of Node.js and supported Linux
  distributions. To learn more about usage, see the repository:
    https://github.com/nodesource/distributions

=======================================================================
=======================================================================

Continuing in 20 seconds ...

**Comment by sbehrens** [comment]
Hi,

I didn't catch we require NodeJS as a dependency.  can you point to me where you saw that step in the wiki or install instructions?

**Comment by sbehrens** [comment]
updated install instructions, thanks for the catch (we don't need to pin to an old version we just use node for asset pipeline management).
