### ISSUE TITLE
Scumblr should track who changed status.

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/Scumblr#25]
On each scumblr result, the top of the page has a number of different statuses.  It would be helpful if the web UI also showed a history of all the status changes performed on a result, and the user who performed those changes.

     Archer@isis.com changed the status from New to Closed on Tuesday.
     Pam@isis.com changed the status from Closed back to New on Wednesday.
     Lanna ... has big hands.

The same goes for any Workflows that were attached to the result.

    Krieger attached the radioactive pig workflow this morning.

Bonus points for using friendly dates with something like http://momentjs.com/

**Comment by sbehrens** [comment]
Closed due to 2.0 Scumblr release, if this is still needed please reopen this ticket or hop in the Scumblr Gitter chat room.
