### ISSUE TITLE
No search results

### ISSUE THREAD

**Issue by riku-akira** [Netflix/Scumblr#27]
I have set up the server API and the CSE. When I run a search nothing comes back. If I do a tcpdump I can see packets going out to Google and then come back. It appears that the API and CSE are working but once the results come back they don't show up in the results page. I followed the install guide for Scumblr and for setting up Google API and CSE (to search the whole internet). Has anyone else had a issue like this?

**Comment by ahoernecke** [comment]
Hi @riku-akira,

To troubleshoot this, could we start by having you run a search manually through the console:

1. From the main scumblr directory run "rails c"
2. Run the following command: SearchProvider::Google.new("scumblr").run

If you could provide the results you receive here or any messages, errors, etc. I'll see if I can help you out.

Thanks!

**Comment by riku-akira** [comment]
So this is what I got:

riku@ubuntu:~/Scumblr$ rails c
SearchProvider::Google.new("scumblr").runLoading development environment (Rails 4.0.9)
[1] pry(main)> SearchProvider::Google.new("scumblr").run
Response received #<Google::APIClient::Result:0x007f5205520a18>
=> []
[2] pry(main)>

**Comment by ahoernecke** [comment]
That would seem to indicate that the search is running and returning, but the API is not returning any results. Have configured your custom search provider to search the entire web?

https://support.google.com/customsearch/answer/2631040?hl=en

**Comment by riku-akira** [comment]
![cse](https://cloud.githubusercontent.com/assets/10149016/5669681/ab7bd8e0-9747-11e4-803c-36f6775b3cf2.JPG)

Well I followed the guide, see anything wrong?

**Comment by ahoernecke** [comment]
What I can see there looks ok, if you do a search over on the right side of the google CSE console are you getting results back?

If so, could you open up the google search provider (/lib/search_providers/google.rb) and update the line that prints out the response (should be line 91) to print out "response.body" instead? So you should be changing line 91 to:

Rails.logger.warn "Response received #{response.body}"

Then rerun the manual search in the console and post the JSON you're getting back?

**Comment by riku-akira** [comment]
[3] pry(main)> SearchProvider::Google.new("scumblr").run
Response received {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "accessNotConfigured",
    "message": "Access Not Configured. The API is not enabled for your project, or there is a per-IP or per-Referer restriction configured on your API key and the request does not match these restrictions. Please use the Google Developers Console to update your configuration.",
    "extendedHelp": "https://console.developers.google.com"
   }
  ],
  "code": 403,
  "message": "Access Not Configured. The API is not enabled for your project, or there is a per-IP or per-Referer restriction configured on your API key and the request does not match these restrictions. Please use the Google Developers Console to update your configuration."
 }
}


![activation](https://cloud.githubusercontent.com/assets/10149016/5670244/376c3666-974c-11e4-8eee-d1469145b904.JPG)

Maybe I have the API set up wrong? I followed the guide and thank you again!

**Comment by ahoernecke** [comment]
Cool, yeah it looks like there is an issue with the api key. If I were to guess, maybe you don't have the Custom Search API turned on for that API key (see screenshot from Google Developer Console)?

![image](https://cloud.githubusercontent.com/assets/655799/5670629/8a59d8b2-9736-11e4-936c-cfb318d77a8d.png)


Let me know if you are unable to fix it. If you do figure it out, please update the issue with the steps your took and let me know you think there is something missing from the documentation.

Thanks and good luck!

**Comment by riku-akira** [comment]
THANK YOU!!!!! Haven't worked with Google API's a lot and of course it would be something simple like this.

**Comment by ahoernecke** [comment]
No problem, glad I could help. Some of those API key configurations are definitely confusing!
