### ISSUE TITLE
Problems with email notofications

### ISSUE THREAD

**Issue by addelindh** [Netflix/Scumblr#28]
We're trying to set up email notifications for saved filters, based on search name. We have tried both the sendmail and smtp option in /config/environments/development.rb but no email is being sent. This is our current config:

  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.perform_deliveries = true
  config.action_mailer.default_url_options = { :host => "localhost:3000", :protocol => 'http' }
  config.action_mailer.default_options = {from: 'user@ourdomain.com'}
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
        address:        '<IP of local outgoing SMTP server>',
        port:           25,
        domain:         'our domain'
   }

We've checked with tcpdump and there are no connections being made to the SMTP at all, when using sendmail there is nothing registered in /etc/log/mail.log

What are we missing?

**Comment by addelindh** [comment]
Note: in the "address" parameter, the IP of our local SMTP server is filled out.

**Comment by ahoernecke** [comment]
A couple things, based on your initial comment:

1. I'm assuming you have a saved filter created that contains results and has a list of email addresses in the subscriber fields?

2. Are you running (manually or via a cron job) the task to send out notifications? There is a rake task called "sync_all" which will run all searches and then (an hour later) send out notifications. 

There is also a "send_email_updates" rake task that can be used independently to send out updates to saved filters without running the searches.
