### ISSUE TITLE
Search time needed

### ISSUE THREAD

**Issue by lazaroskyr** [Netflix/Scumblr#30]
Hello everyone and thanks for this great tool.

I know that a number of people is asking about searches, etc, but please allow me to ask again about a slightly different issue than the ones already asked. 

I have created the API Key and the Custom Search ID from Google. I have included them in the configuration file and restarted the application. 

I now try to create a search, and I am required to give the Custom Search ID again (I guess is the same as the one in the file) and fill in the rest of the fields needed. I do that. However, the search is not returning any results. I know that these tools usually require a large amount of time to conclude a search, but how much is a reasonable amount of time that I need to wait for? The page seems stuck on the "Running Search" for a couple of hours now.

Any help will be much appreciated.

**Comment by lazaroskyr** [comment]
I also detected another issue: I see that the processes don't stop. I am "killing" them, but they keep "coming back". What am I doing wrong?

**Comment by ahoernecke** [comment]
Hi @lazaroskyr,

A couple things... When you create a search, providing the custom search id is optional assuming you already have it in the configuration file. You can use this to override the default custom search id if you have more than one. If you want to use the custom search engine from the config file, just leave the field blank when you create the search.

For the built-in search providers, searches shouldn't take more than a couple seconds. Once you click "Run search", the search task will be backgrounded and should complete pretty quickly. You'll need to go to the Results page to see if results were found. You should be able to tell if the search has completed by looking at the "Tasks" in the upper right corner. If this is 0, it should mean nothing is currently running (i.e. everything has completed)

**Comment by lazaroskyr** [comment]
Unfortunately it is stuck on "Running Search" and there is nothing in the "Results" section. Also the "Tasks" is always 0...

I don't know what the problem is.

**Comment by lazaroskyr** [comment]
It was my stupid stupid mistake. I haven't enabled the "Custom Search API".
I must have skipped the step when setting it up.

I apologize for this. Anyway, thank you very much Andy.

**Comment by ahoernecke** [comment]
No worries, glad you got it working!
