### ISSUE TITLE
Option to whitelist sites

### ISSUE THREAD

**Issue by plaverty24** [Netflix/Scumblr#33]
When you click on the link to view the content, you get the popup warning that it could be taking you to a dangerous site. That gets annoying every time, so how about an option to whitelist certain domains so that popup doesn't show? If I want, I can add twitter.com and pastebin.com to not show the popup warning and I go straight to the site if that is the domain.

**Comment by ahoernecke** [comment]
Hi @plaverty24,

Thanks for the suggestion. This sounds reasonable. If you'd like to create the functionality and submit a pull request I'd be happy to review and merge it in. Otherwise, I've added this to our backlog as an feature request. 

Thanks!

**Comment by plaverty24** [comment]
Thanks Andy, unfortunately I don't know Ruby, or I'd be happy to add it.
Thanks for putting it on the list.

**Comment by frsh2fourty** [comment]
I've found an easy work around to this is to right click>open in new tab to avoid the warning popup.

**Comment by alumbs** [comment]
I would like to help out with this feature. I'm guessing I should add a whitelist file somewhere in the config folder, reference that file in these pages '_show_details.html.erb', '_results_table.html.erb', and 'notification.html.erb', and only show the 'Are you sure...' message if the url is not amongst the whitelist urls. Sound good?

**Comment by ahoernecke** [comment]
Hi @alumbs,

Did you you notice frsh2fourty's work around for this? Since clicking the click (and then OK) opens in a new tab anyways, I'm wondering if just doing the right click>open in new tab is sufficient for your use cases. I feel like maintaining a whitelist of sites to prompt/not to prompt seems a little heavy weight for the size of the problem.

Maybe a simpler solution would be having a setting in the scumblr initializer that globally disables the message instead of having to maintain a whitelist?

Thoughts?

**Comment by alumbs** [comment]
I completely agree. I think having a setting in the scumblr initializer is a nice and simple solution to this issue. Would we need to add that setting to the UI so that users can turn it On/Off, or just make it a setting that can be adjusted in the code?

**Comment by ahoernecke** [comment]
I'd be fine just adding it to the scumblr initializer as a global setting (in code).

**Comment by alumbs** [comment]
Hi sorry for the delay, I've been going through some Rails tutorial to try to understand how to 1. Set a variable in the config file, and 2. Access the variable in the view and show the 'confirm' option depending on the value of the variable.

So far, the tutorials haven't mentioned config files, but I'll figure it out soon.

**Comment by sbehrens** [comment]
Closed due to 2.0 Scumblr release, if this is still needed please reopen this ticket or hop in the Scumblr Gitter chat room.
