### ISSUE TITLE
basic setup trouble shooting

### ISSUE THREAD

**Issue by tDorosheff** [Netflix/Scumblr#36]
Running scumblr on ubuntu 3.13 with all the prerequisites installed.

So far I have followed the setup wiki, step by step, up to the point where it is time for me to try connecting to scumblr on port 3000. When i try to navigate to the sign in page via my browser (have tried both chrome and firefox) i get a connection timed out. I know that i can connect to other services that are hosted on my scumblr box, so i dont believe it is a general network issues. Also I have tried doing a wget to 0.0.0.0:3000 from the box itself, just to see if the service actually started. When i did this i successfully downloaded an index.html page with all the right looking stuff in it; "title>Scumblr</title"
.....
"h1>Scumblr</h1<br
      h3>Trolling the garbage dump that is the Internet, so you don't have to.</h3"
.....
"form accept-charset="UTF-8" action="/users/sign_in" class="simple_form new_user" id="new_user" method="post""
.....

What things should i look for at this point, that could be causing the issue? This is the second time ive set up scumblr, the first was on a cent5 box which i was able to set up successfully. I have apache running on the box and i was able to get to the web root on port 80, from my other workstation.

**Comment by tDorosheff** [comment]
i nmapped the box from itself and from my other workstation, and can see that port 3000 is open locally, but not showing when scanned remotely.

**Comment by ahoernecke** [comment]
Hi @tDorosheff,

It sounds like either the rails server is not binding to your external ip address(es), or there is some other firewall in place that is preventing you from connecting.

You may want to try the rails server -b option to ensure you're listen on your external interfaces.

The following command should bind to all interfaces.
```
rails s -b 0.0.0.0
```
