### ISSUE TITLE
How can I disable the http -> https redirection in Production mode.

### ISSUE THREAD

**Issue by xitation** [Netflix/Scumblr#42]
Hi there,

I've found that when running in production mode it appears that an automatic 301 redirect takes place when hitting the site on http://localhost:3000 to https://hostname/.

Started GET "/" for 127.0.0.1 at 2015-04-01 10:38:33 +1100
Processing by ResultsController#index as HTML
Completed 401 Unauthorized in 2ms
Started GET "/users/sign_in" for 127.0.0.1 at 2015-04-01 10:38:34 +1100
Processing by Devise::SessionsController#new as HTML
Redirected to https://localhost/users/sign_in
Filter chain halted as #<Proc:0x007fef97cc9b68@/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/actionpack-4.0.9/lib/action_controller/metal/force_ssl.rb:65> rendered or redirected
Completed 301 Moved Permanently in 2ms (ActiveRecord: 0.0ms)

This is a problem as the way I will be using this will be via SSH tunnel only, it will never be published externally. 

I'm wondering how I can remove the auto redirection, or if this can be turned into an optional feature that can be configured on or off.

Thanks.

**Comment by ahoernecke** [comment]
You should be able to remove (comment out or delete) the following line from the application_controller.rb file (line 29):

```
force_ssl if: :ssl_configured?
```

Also update the default protocol under config/environments/production.rb (line 92):
```
Rails.application.routes.default_url_options[:protocol] = "http"
```

**Comment by xitation** [comment]
I tried that, but it seems some routes might need to be fixed too, which was beyond my level of ruby/rails knowledge to solve at this stage. 

Started GET "/stylesheets/application.css" for 127.0.0.1 at 2015-04-02 13:27:09 +1100
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
* snip

Started GET "/javascripts/application.js" for 127.0.0.1 at 2015-04-02 13:27:09 +1100
ActionController::RoutingError (No route matches [GET] "/javascripts/application.js"):
* snip

Started GET "/javascripts/vendor/modernizr.js" for 127.0.0.1 at 2015-04-02 13:27:09 +1100
ActionController::RoutingError (No route matches [GET] "/javascripts/vendor/modernizr.js"):
* snip

Started GET "/images/scumblr.svg" for 127.0.0.1 at 2015-04-02 13:27:09 +1100
ActionController::RoutingError (No route matches [GET] "/images/scumblr.svg"):

etc.

The page loads, but also isn't rendered correctly none of the graphics or styling is show, which would make sense as it seems it can't get to the stylesheets etc.

![2-04-2015 1-29-53 pm](https://cloud.githubusercontent.com/assets/1818975/6956565/70dfad2e-d93c-11e4-86ac-5fa375572513.png)

**Comment by xitation** [comment]
Well after additional digging I managed to figure out a solution.

You need to edit "app/controllers/application_controller.rb" and as suggested by @ahoernecke comment out line 29 "#force_ssl if: :ssl_configured?"

You also need to edit "config/environments/production.rb" and edit line 32 "config.serve_static_assets = true" setting it to true.

Then you need to run the following: "rake assets:precompile" 

Then re-restart scumblr and it should be good to go.

**Comment by goobertron90** [comment]
I have the same exact issue as @xitation. I made the same changes, except I did not mess with my route.rb file. Now I go to 0.0.0.0 and get redirected to http://0.0.0.0:3000/usrs/sign_in I get a 500 error "We're sorry, but something went wrong." 

ActiveRecord::StatementInvalid (Could not find table 'users'):
  activerecord (4.0.9) lib/active_record/connection_adapters/sqlite3_adapter.rb:515:in `table_structure'
  activerecord (4.0.9) lib/active_record/connection_adapters/sqlite3_adapter.rb:402:in `columns'
  activerecord (4.0.9) lib/active_record/connection_adapters/schema_cache.rb:114:in `block in prepare_default_proc'
  activerecord (4.0.9) lib/active_record/connection_adapters/schema_cache.rb:56:in `yield'
  activerecord (4.0.9) lib/active_record/connection_adapters/schema_cache.rb:56:in `columns'
  activerecord (4.0.9) lib/active_record/model_schema.rb:208:in `columns'
  activerecord (4.0.9) lib/active_record/model_schema.rb:217:in `columns_hash'
  activerecord (4.0.9) lib/active_record/inheritance.rb:176:in `subclass_from_attributes?'
  activerecord (4.0.9) lib/active_record/inheritance.rb:23:in `new'
  devise (3.3.0) app/controllers/devise/sessions_controller.rb:9:in `new'
  actionpack (4.0.9) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.0.9) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.0.9) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.0.9) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (4.0.9) lib/active_support/callbacks.rb:453:in `_run__4600110910908974585__process_action__callbacks'
  activesupport (4.0.9) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.9) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (4.0.9) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.0.9) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.0.9) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.9) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.9) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.0.9) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.0.9) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.0.9) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.0.9) lib/abstract_controller/base.rb:136:in `process'
  actionpack (4.0.9) lib/abstract_controller/rendering.rb:44:in `process'
  actionpack (4.0.9) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.0.9) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.0.9) lib/action_controller/metal.rb:231:in `block in action'
  actionpack (4.0.9) lib/action_dispatch/routing/route_set.rb:82:in `call'
  actionpack (4.0.9) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.0.9) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.0.9) lib/action_dispatch/routing/mapper.rb:44:in `call'
  actionpack (4.0.9) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.0.9) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.0.9) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.0.9) lib/action_dispatch/routing/route_set.rb:676:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.0.9) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.0.9) lib/action_dispatch/middleware/flash.rb:241:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.0.9) lib/action_dispatch/middleware/cookies.rb:486:in `call'
  activerecord (4.0.9) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.0.9) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  actionpack (4.0.9) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.0.9) lib/active_support/callbacks.rb:373:in `_run__3823255678553440280__call__callbacks'
  activesupport (4.0.9) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.9) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.0.9) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.0.9) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.0.9) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.9) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.9) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.9) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.0.9) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.0.9) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.0.9) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.0.9) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.9) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.0.9) lib/rails/engine.rb:511:in `call'
  railties (4.0.9) lib/rails/application.rb:97:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  unicorn (4.8.3) lib/unicorn/http_server.rb:576:in `process_client'
  unicorn (4.8.3) lib/unicorn/http_server.rb:670:in `worker_loop'
  unicorn (4.8.3) lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
  unicorn (4.8.3) lib/unicorn/http_server.rb:140:in `start'
  unicorn-rails (2.1.1) lib/unicorn_rails.rb:26:in `run'
  rack (1.5.2) lib/rack/server.rb:264:in `start'
  railties (4.0.9) lib/rails/commands/server.rb:84:in `start'
  railties (4.0.9) lib/rails/commands.rb:76:in `block in <top (required)>'
  railties (4.0.9) lib/rails/commands.rb:71:in `tap'
  railties (4.0.9) lib/rails/commands.rb:71:in `<top (required)>'
  script/rails:6:in `require'
  script/rails:6:in `<main>'


any ideas?

**Comment by ahoernecke** [comment]
Your error there is "Could not find table 'users'". That would seem to indicate that your database config file isn't point to the right db, you haven't created a db (rake db:create) or your migrations weren't run or railed for some reason (rake db:migrate).

Can you make sure your database is all setup properly and see if that helps?

**Comment by goobertron90** [comment]
I already ran "rake db:create" during setup, but it looks like that was only for development environment because when I re-ran "rake db:create" i got this output, "db/development.sqlite3 already exists" which is not what I want. I probably want a production db, correct? How can I correct this?

**Comment by goobertron90** [comment]
Hey @ahoernecke I figured it out. I must have messed with something prior to running those steps. I went back to my snapshot and performed those steps again and it worked great. Thanks!

**Comment by ahoernecke** [comment]
Great, glad you got it working!
