### ISSUE TITLE
Logging in Scumblr Failure

### ISSUE THREAD

**Issue by kingstone1** [Netflix/Scumblr#43]
Hi guys,

I am experiencing an issue when trying to sign in scumblr web page (0.0.0.0:300) after creating an admin user. I have followed the documentation on the wiki page step by step but cant see anything wrong. Though, i have made scumblr working few weeks ago. 

I tried installing scumblr again on various boxes but i cant log in anymore. I have recently read online about an issue with Rails after the upgrade on the cookie_serializer.rb. I tried removing the Rails.application.config.action_dispatch.cookies_serializer = :json as I have seen on this post (https://github.com/plataformatec/devise/issues/2949) but i still cannot log in.

In addition, I tried generating secret keys on devise.rb as well as secret_token.rb but no luck so far and i was hoping if anybody from the community could help.

I run scumblr from the command line from the Scumblr root folder as it is outlined on the wiki page and  going to 0.0.0.0:3000, on the terminal I can see the following below, which seems fine:

Started GET "/users/sign_in" for 127.0.0.1 at 2015-04-07 14:02:20 +0100
Processing by Devise::SessionsController#new as HTML
  Rendered devise/shared/_links.erb (0.4ms)
  Rendered devise/sessions/new.html.erb within layouts/devise (58.0ms)
Completed 200 OK in 315ms (Views: 297.4ms | ActiveRecord: 1.3ms)

Started GET "/users/sign_in" for 127.0.0.1 at 2015-04-07 14:02:21 +0100
Processing by Devise::SessionsController#new as */*
  Rendered devise/shared/_links.erb (0.1ms)
  Rendered devise/sessions/new.html.erb within layouts/devise (3.5ms)
Completed 200 OK in 11ms (Views: 9.8ms | ActiveRecord: 0.0ms)

Then when trying to sign in it fails by saying invalid email or password on the Scumblr page..Checking on the terminal though, i get the 401 Unauthorized (see below)

Started POST "/users/sign_in" for 127.0.0.1 at 2015-04-07 14:03:49 +0100
Processing by Devise::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"YdCNqpOgawbo514xIXY8Hs/P76nY10cRG5zGWB3L1yI=", "user"=>{"email"=>"myemail@xxx.com", "password"=>"[FILTERED]"}, "commit"=>"Sign in"}
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."email" = 'myemail@xxx.com' ORDER BY "users"."id" ASC LIMIT 1
Completed 401 Unauthorized in 49ms
Processing by Devise::SessionsController#new as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"YdCNqpOgawbo514xIXY8Hs/P76nY10cRG5zGWB3L1yI=", "user"=>{"email"=>"myemail@xxx.com", "password"=>"[FILTERED]"}, "commit"=>"Sign in"}
  Rendered shared/_notification.html.erb (0.3ms)
  Rendered devise/shared/_links.erb (0.0ms)
  Rendered devise/sessions/new.html.erb within layouts/devise (4.4ms)
Completed 200 OK in 64ms (Views: 10.6ms | ActiveRecord: 0.0ms)

Started GET "/users/sign_in" for 127.0.0.1 at 2015-04-07 14:03:49 +0100
Processing by Devise::SessionsController#new as */*
  Rendered devise/shared/_links.erb (0.0ms)
  Rendered devise/sessions/new.html.erb within layouts/devise (3.5ms)
Completed 200 OK in 11ms (Views: 9.6ms | ActiveRecord: 0.0ms)

Please note the email address is a valid email. I have just replaced it with myemail@xxx.com when posting this.

Thank in advance,
Nick

**Comment by ahoernecke** [comment]
Hey Nick,

Haven't run into this before. Have you tried reseting your password from the rails console to ensure you're using the correct password?

**Comment by ahoernecke** [comment]
Closing due to lack of update. Please reopen if this is still an issue.

**Comment by arun-kuriakose** [comment]
Having the same issue ...please help

**Comment by ahoernecke** [comment]
Hi @arun-kuriakose,

Can you provide some more details about your situation? What exactly is the problem and what steps have to taken to attempt to fix the situation?

Thanks
