### ISSUE TITLE
Search Not Working

### ISSUE THREAD

**Issue by zurdo-pr** [Netflix/Scumblr#44]
When trying to do a search the task never runs . When looking at the sidekig.log , Im getting a

ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

**Comment by ahoernecke** [comment]
Hi @zurdo-pr,

I'm not sure how to help you out without some additional details. It obviously looks like scumblr is running into an SSL issue when connecting to the search provider, but I'm not sure why that would be happening. 

Which search provider are you using? Is your system traffic flowing through a proxy of some type?

**Comment by ahoernecke** [comment]
Hi @zurdo-pr,

If you could provide some details on the issue you were running into and how you fixed it, I'd be good to know to help anyone else that runs into similar issues.

Thanks!
