### ISSUE TITLE
undefined method `channel' for #<RSS::Atom::Feed:0x0000000886e310>

### ISSUE THREAD

**Issue by jwilczek** [Netflix/Scumblr#45]
When trying to pull information from RSS feeds, I receive the error "ERROR: undefined method `channel' for #<RSS::Atom::Feed:0x0000000886e310>" in my sidekiq log and it appears that I'm never getting any input from RSS feeds.  Any thoughts on why this would be?

OK, since posting this I believe I've figured out the issue.  I was trying to use a Google Alert as my RSS feed and they do not contain a "channel" tag.  Would it be possible to add the ability to support Google Alert RSS Feeds?

**Comment by ahoernecke** [comment]
Hi @jwilczek,

Apparently google alerts uses atom feeds which are formatted a little differently. I just pushed up a commit to master which should work for either rss/atom feed. Try it out and let me know if you have any issues.

**Comment by jwilczek** [comment]
Thank you!  I’ll check it out and let you know.

 

Josh
