### ISSUE TITLE
Facebook Search Error

### ISSUE THREAD

**Issue by mativ** [Netflix/Scumblr#46]
I have set up the appid and app secret in Scumbler. When I attempt to do a facebook search I get the following error from sidekiq.

2015-05-08T01:44:57Z 10593 TID-oxdmyxsrg SearchRunner JID-ec1bfe9fd727a620929c8efe INFO: start
2015-05-08T01:44:57Z 10593 TID-oxdmyxsrg SearchRunner JID-ec1bfe9fd727a620929c8efe WARN: **Search id: 18
2015-05-08T01:44:57Z 10593 TID-oxdmyxsrg SearchRunner JID-ec1bfe9fd727a620929c8efe WARN: Searching #<Search:0x007fea66ea1d40>
2015-05-08T01:44:57Z 10593 TID-oxdmyxsrg SearchRunner JID-ec1bfe9fd727a620929c8efe ERROR: type: OAuthException, code: 1, message: An unknown error has occurred. [HTTP 500]
2015-05-08T01:44:57Z 10593 TID-oxdmyxsrg SearchRunner JID-ec1bfe9fd727a620929c8efe INFO: done: 0.429 sec

I saw facebook search deprecation in issue, but I believe this is a different error.

**Comment by ahoernecke** [comment]
Hi @mativ,

Can you post a redacted version of your scumblr.rb initializer? If you're comfortable, could you pop into the rails console and run the perform_search search method on a search you have setup with the Facebook provider and post the results? Hopefully you'll get a stack trace..

For example, if the last search you created uses Facebook you should be able to do the following in the console:
```
search = Search.last
search.perform_search
```

**Comment by ahoernecke** [comment]
I'm going to close this issue as there hasn't been a response in over a month. If this is still an issue please feel free to reopen with the requested information.

**Comment by enasda** [comment]
I get result when I search using facebook provider for some queries but there are other queries doesn't return results although I am sure it is existed on facebook, when I performed manual search as listed above I got the following error:

>  pry(main)> search.perform_search
Searching Search 16
Results
  Status Load (0.2ms)  SELECT "statuses".* FROM "statuses" WHERE "statuses"."default" = 't' LIMIT 1
NoMethodError: undefined method `each' for nil:NilClass
from /home/test/Scumblr/app/models/search.rb:114:in `perform_search'

**Comment by ahoernecke** [comment]
Hi @enasda,

Are you using the latest version of the facebook plugin? Can you provide some general details on what you're searching for? Based on the log it looks like your search is returning "nil". Based on the code of the facebook search a little confused as to how that would be happening.

**Comment by enasda** [comment]
Hi @ahoernecke ,
thanks for replying, my API version is v2.6, and I am searching for mentioning of certain persons name.

**Comment by ahoernecke** [comment]
Hmm, can you try this query running the search provider like this and see if you get results (you should get a list of results but it won't add anything to the database):
```
SearchProvider::Facebook.new("netflix").run
```

If that seems to work try the same with your query instead of netflix:
```
SearchProvider::Facebook.new( SEARCH_QUERY_HERE ).run
```

Let me know what the output looks like.

**Comment by enasda** [comment]
the first search worked and return results but when I put my query I get:
ps. I am looking for name from two parts (firstname lastname)

![image](https://cloud.githubusercontent.com/assets/20086864/16397817/5d0624c0-3ccf-11e6-85da-61e8850c5743.png)

**Comment by enasda** [comment]
Hey,
is there any update regards this issue?

**Comment by ahoernecke** [comment]
Hi @enasda,

Unfortunately I think you're running into the limitations on Facebook's new public API. It used to be possible to search all public updates on Facebook, but they changed the API and now what you're able to search is more limited. To maximize results, the facebook search looks for Facebook pages based on the query and then gets the posts for those pages.

Since you're able to get results for some searches but not others, it that the Facebook apis is not returning any results for that specific query, and that's a limitation of the Facebook APIs.

If you are aware of a way to tweak the Facebook search provider so that it is able to find better results, please submit a pull request and I'll review.

Thanks!
