### ISSUE TITLE
Problems with Google Search set-up

### ISSUE THREAD

**Issue by jiolwell** [Netflix/Scumblr#52]
Hello, I am having some trouble being able to set-up and run Google search from Scumblr.  When I try to use the searches, I get no results back.  I have my Server API key and Custom Search Engine set-up, and I can get results if I use the Search Engine directly.

I have looked at earlier issues that were closed, and tried some of those remedies.  When I use rails c and the command " SearchProvider::Google.new("scumblr").run", I get the following.

Google::APIClient::ClientError: Bad Request
from /home/<username>/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/google-api-client-0.7.1/lib/google/api_client.rb:618:in `block in execute!'

I'm pretty new with Ruby, so I'm not ruling out simple mistakes I'm not seeing.

**Comment by ahoernecke** [comment]
Hi @jiolwell,

Could you post a redacted version of your scumblr.rb initializer file? I would double check your google developer key. I can reproduce this error is I put an invalid google developer key into the config file.

**Comment by jiolwell** [comment]
Scumblr::Application.configure do
  # Should Scumblr automatically generate screenshots for new results
  # config.sketchy_url = "http://localhost:80/api/v1.0/capture"
  # config.sketchy_use_ssl = false  # Does sketchy use ssl?
  # config.sketchy_verify_ssl = true # Should scumblr verify sketchy's cert
  # config.sketchy_tag_status_code = true # Add a tag indicating last status code sketchy received
  # config.sketchy_access_token = "" # Access token for sketchy

  # Provider configurations

  #config.ebay_access_key = ''

  #config.facebook_app_id = ''
  #config.facebook_app_secret = ''

  config.google_developer_key = '*****************************************'
  config.google_cx  = '*****************************'
  config.google_application_name = 'Scumblr'
  config.google_application_version = '1.0'

  #config.youtube_developer_key = ''
  #config.youtube_application_name = ''
  #config.youtube_application_version = ''

  #config.twitter_consumer_key        = ''
  #config.twitter_consumer_secret     = ''
  #config.twitter_access_token        = ''
  #config.twitter_access_token_secret = ''


end

**Comment by ahoernecke** [comment]
Is the key you're using a key for browser applications or server applications? Do you have referrer or IP restrictions enabled? Have you confirmed that you copied the complete/correct value into the config file? (See screenshot)
![screen shot 2015-07-16 at 12 59 23 pm](https://cloud.githubusercontent.com/assets/655799/8734003/df4bc99c-2bbb-11e5-8723-ca96092d9aa3.png)

**Comment by jiolwell** [comment]
I double checked, and inputted the key again, and this time it worked.  Must have been a mistype on my part.  I'm starting to get results now, although it seems to be capped at 10 results per search, which seems odd considering I'm running searches for things like "netflix scumblr" and "tutorial" and "google" which should be getting more results back.  

Appreciate the help!

**Comment by alumbs** [comment]
Hi jiolwell, the issue you are experiencing with the search result being capped at 10 results, was solved in issue 19 https://github.com/Netflix/Scumblr/issues/19. The issue, as mentioned in issue 19, occurs because the google api only returns 10 results per search request. The remedy was to change the code from step(100) to step(10). Take a closer look at issue 19 for more details.

Hope that helps.

**Comment by jiolwell** [comment]
alumbs,

That did the trick!  Appreciate the help, I'm getting a lot more results with google search now.  So I think I'm all good now.
