### ISSUE TITLE
rake task issue

### ISSUE THREAD

**Issue by tDorosheff** [Netflix/Scumblr#53]
I successfully ran all searches using the "rake sync_all" command from the back end. I then tried again, about 10 minutes later to do it again, this time i wanted to know if the screenshots would also be taken as part of the rake task. However no searches ran, and my rake task seemed to just sit there with the following output to std out: "2015-07-16T13:00:23Z 3267 TID-oqzy2jc7g INFO: Sidekiq client with redis options {}" I waited for a little bit and then just aborted the task. This is where i saw the line "/home/Scumblr/Scumblr/lib/tasks/sync_tasks.rake:11:in `sleep' ". So i took a look at sync_tasks.rake and sure enough on line 11 was a line basically saying to sleep 1 hour after a rake task. I changed it to "sleep(10.minutes)" thinking that this would have an effect, but no luck. Now, certainly an hour has passed since the first rake, and it still hangs/sleeps.

**Comment by ahoernecke** [comment]
Hi @tDorosheff, 

Can you be a little more specific on exactly what you think the issue you're seeing is? Are the screenshots just never being requested? 

For some background context, the sleep was put in place as a naive way of ensuring the searches would be finished before attempting to take screenshots. You should be able to shorten this significantly assuming you don't have long running or a huge number of searches.

There is a pretty big update coming soon that addresses the issue of needing the sleep, and the general desire to have certain tasks that run after others, in a more deliberate way. But in the meantime, the functionality should work, so if you're not seeing screenshots being requested we should be able to figure out why.

**Comment by tDorosheff** [comment]
Im not seeing anything happen at all. When i run the rake sync_all command, i usually see searches get run, and during the first execution of the rake task, i did. However it was during the second run that nothing happened.

**Comment by ahoernecke** [comment]
Are you seeing this behavior consistently? If you run the rake tasks twice, does the second ones never seem to run the searches? Have you restarted sidekiq and tried again?
