### ISSUE TITLE
Programatically create searches, or create bulk searches

### ISSUE THREAD

**Issue by tDorosheff** [Netflix/Scumblr#56]
Have a long list of domains that i want to query google for. The list contains a domain, and then 3 or 4 "inurl:value" parameters, for each domain.  Is there a way to create searches in the backend of Scumblr? How best should i go about getting around 70-80 domains each one having 3 or 4 inurl:value parameters into searches?

**Comment by tDorosheff** [comment]
if theres no way to programatically build searches, how big can i build a single search? Can i have a single search be something like this:

site:1.com OR site:2.com OR site:3.com ..... OR site:200.com OR inurl:this.html OR inurl.that.html OR inurl:these.html

**Comment by ahoernecke** [comment]
Hey @tDorosheff,

You can programmatically build searches through the rails console if you wanted to do that:

```
Search.create(name: "name for the search", description: "description for the search", query: "the query", search_provider: "SearchProvider::Google", options: "")
```

To create a bunch of them you'd just need to get a list of what you wanted to create, and run a loop around that create call.

If you need additional options besides the query (like a custom cx) it may be easiest to create one search through the UI then in the console run:

```
Search.last
```

to see how the custom options get formatted. Then you could copy that over to your new searches.

One other thought... if you're running the same search across a bunch of different domains, it may be an option to create a custom search engine in google scoped to only these domains. I'm not sure if this would give you example what you want though.

**Comment by tDorosheff** [comment]
alright i tried out the for loop approach with this:

IO.foreach("test.txt") {|x| print Search.create(name: x, description: "webshell search on " x, query: "site: x inurl:c99.php OR inurl:r57.php OR inurl:b374k.php", search_provider: "SearchProvider::Google", options:"" x,)}

Everything works well until i get to the "query:" part. The loop builds the search query, where name = value_of_x_variable, description = "webshell search on value_of_x_variable", query = "site:x inurl:c99.php OR inurl:r57.php....etc

It queries for site:"x" literally instead of the actual value of the x variable. I think i need to figure out how to refer to the x variable instead of the literal character "x" from inside quotes. I also tried doing this:
query: "site: " x, "inurl:c99.php OR inurl:r57.php OR inurl:b374k.php", search_provider: "SearchProvider::Google", options:"" x,)}

breaking the quotes and leaving the x variable quotless, which seemed to work for the other attributes in the create call, but with those other variables I was inserting the x variable at the end of the attribute.

**Comment by ahoernecke** [comment]
Unless github is munging your code (may try the code snippet markup) it looks like you're doing a combination of putting the x variable inline next to a string for concatenation (which won't work) and including it directly inside a string--which is just interpreted as the character x.

Try syntax like this:
```
IO.foreach("test.txt") { |x| 
  Search.create(name: x, description: "webshell search on #{x}", query: "site:#{x} inurl:c99.php OR inurl:r57.php OR inurl:b374k.php", search_provider: "SearchProvider::Google")
}
```

**Comment by tDorosheff** [comment]
bingo that did it

**Comment by ahoernecke** [comment]
Sweet, happy Scumbling!
