### ISSUE TITLE
I need to integrate Scumblr with my application, but i can't find any api in Scumblr for that. Do Scumblr have api support?

### ISSUE THREAD

**Issue by coolnimesh43** [Netflix/Scumblr#58]
I have installed Scumblr and it is working fine. It has all the things i was looking for and i love it. I want to use the search results provided by Scumblr into my application. But i was not able to find any documentation about integration api. Does Scumblr has any api exposed for integration with other application? If yes, please provide me the documentation. Any help is appreciated. 

Thank You.

**Comment by ahoernecke** [comment]
Hi Nimesh,

Scumblr has some limited API support but it's kind of unofficial and it's not currently documented. Basically I have added some API functionality for a couple specific use cases as needed, but it's never really been fully/formally developed.

A couple things you can do:

1. Result search--You can get a list of search results by adding ".json" or a parameter (format=json) to the search. For example: https://scumblr/results/search?url_cont=netflix&format=json (could use post parameters for longer queries as well)
2. Result details--You can get limited details of an individual result by adding ".json" or a parameter (format=json) to the result's url (https://scumblr/results/123.json)

Could you provide some details on what you'd like to access/do with an API?

**Comment by coolnimesh43** [comment]
I am developing a java application that performs adverse media search. Its just a side project to hone my programming skills.  Scumblr seems to fit perfectly for searching the social media content. I want to do sentiment analysis on the result data.

**Comment by ahoernecke** [comment]
So based on that, I'm guessing you could probably setup a search in scumblr to track what you were interested in, and then your Java application could periodically pull those results and, from the url, get the content and do your sentiment analysis.

Does this make sense? If you have recommendations for improving this, let me know.
