### ISSUE TITLE
rake sync_all doesnt take screenshots.

### ISSUE THREAD

**Issue by LutherWest** [Netflix/Scumblr#59]
In the documentation it says "This take will run all the searches and import any new results. It will also generate screenshots of each result, if the integration with Sketchy is configured."

Unfortunately, although it does do the searches properly, I can't get to make it generate screenshots automatically.I believe Sketchy is configured correctly because I can get screenshots manually from the attachments area in Scumblr.

**Comment by ahoernecke** [comment]
Hey @LutherWest,

The sync_all task code basically just runs a task to run all the searches, waits an hour and then runs a task to generate screenshots... So first make sure you've waited an hour or so to scumblr a chance to request the screenshots and sketchy a chance to return them.
```
 # Run all searches
  Rake::Task["perform_searches"].invoke
  
  # Sleep 1 hours to ensure all search tasks have complete
  sleep(1.hour)

  # Generate screenshots
  Rake::Task["generate_screenshots"].invoke
```

Could you try running the following command directly from the command line
```
rake generate_screenshots
```

**Comment by LutherWest** [comment]
That's a mistake on my behalf, I apologize.

I only read the docs by the time of posting and I just logged-in to resolve the issue now that I read the code. Although, I'm having one last issue with the mailing. Would you like me to just post it here or close this one and open another?
