### ISSUE TITLE
No result returned Google Search 

### ISSUE THREAD

**Issue by baraths84** [Netflix/Scumblr#62]
Hi All, @romain-nio @ahoernecke I have an similar issue with google search. I defined my google key and google cx but i am still seeing  "Running search... " for a long time. I see the Tasks tab showing 1 and stopping.

Can you please advise.  I followed the steps here but i still encounter the issue https://github.com/Netflix/Scumblr/issues/3

**Comment by ahoernecke** [comment]
Hello @baraths84, Do you have redis and sidekiq running? Can you post the logs from sidekiq?

**Comment by baraths84** [comment]
Thank you.
