### ISSUE TITLE
Syntax Error Trying to Send Email Upates

### ISSUE THREAD

**Issue by jwilczek** [Netflix/Scumblr#63]
I'm trying to use sendmail to send email updates.  I believe I've followed the directions properly in that I've created a new filter and have new results within that filter.  When running the command: 

RAILS_ENV=production bundle exec rake send_email_updates --trace

I get the following output (which appears to be related to the query for new results?)

RAILS_ENV=production bundle exec rake send_email_updates --trace
** Invoke send_email_updates (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute send_email_updates
rake aborted!
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near ")"
LINE 1: ... ILIKE '%test%' AND "results"."status_id" NOT IN () AND "res...
                                                             ^
: SELECT DISTINCT COUNT(DISTINCT "results"."id") FROM "results"  WHERE (("results"."url" ILIKE '%test%' AND "results"."status_id" NOT IN () AND "results"."created_at" > '2015-11-08 14:26:31.012293' AND "results"."created_at" < '2015-11-08 14:29:01.362157'))
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/postgresql_adapter.rb:798:in `async_exec'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/postgresql_adapter.rb:798:in `exec_no_cache'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/postgresql/database_statements.rb:138:in `block in exec_query'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/abstract_adapter.rb:442:in `block in log'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/postgresql_adapter.rb:915:in `select'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/abstract/database_statements.rb:25:in `select_all'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/abstract/query_cache.rb:64:in `select_all'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/relation/calculations.rb:262:in `execute_simple_calculation'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/relation/calculations.rb:224:in `perform_calculation'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/relation/calculations.rb:108:in `calculate'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-deprecated_finders-1.0.3/lib/active_record/deprecated_finders/relation.rb:84:in `calculate'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/relation/calculations.rb:24:in `count'
/mnt/data/apps/Scumblr/lib/tasks/sync_tasks.rake:44:in `block (2 levels) in <top (required)>'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/relation/delegation.rb:13:in `each'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/relation/delegation.rb:13:in `each'
/mnt/data/apps/Scumblr/lib/tasks/sync_tasks.rake:36:in `block in <top (required)>'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
PG::SyntaxError: ERROR:  syntax error at or near ")"
LINE 1: ... ILIKE '%test%' AND "results"."status_id" NOT IN () AND "res...
                                                             ^
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/postgresql_adapter.rb:798:in `async_exec'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/postgresql_adapter.rb:798:in `exec_no_cache'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/postgresql/database_statements.rb:138:in `block in exec_query'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/abstract_adapter.rb:442:in `block in log'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/postgresql_adapter.rb:915:in `select'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/abstract/database_statements.rb:25:in `select_all'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/connection_adapters/abstract/query_cache.rb:64:in `select_all'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/relation/calculations.rb:262:in `execute_simple_calculation'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/relation/calculations.rb:224:in `perform_calculation'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/relation/calculations.rb:108:in `calculate'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-deprecated_finders-1.0.3/lib/active_record/deprecated_finders/relation.rb:84:in `calculate'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/relation/calculations.rb:24:in `count'
/mnt/data/apps/Scumblr/lib/tasks/sync_tasks.rake:44:in `block (2 levels) in <top (required)>'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/relation/delegation.rb:13:in `each'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.9/lib/active_record/relation/delegation.rb:13:in `each'
/mnt/data/apps/Scumblr/lib/tasks/sync_tasks.rake:36:in `block in <top (required)>'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/mnt/data/apps/Scumblr/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => send_email_updates

**Comment by ahoernecke** [comment]
Hi @jwilczek, 

Haven't seen this before, but looking at the query that's being generated, I have a hypothesis. It looks like you don't have statuses setup (or at least, you don't have a status with the closed attribute set to true). Also, it looks like when you created your saved filter you did not check the "include closed results" check box. So it looks the query being generated is invalid because we're trying to filter out closed results, but there are no status ids to filter to.

If this is correct, I think you should be able to do one of two quick fixes: 

First, you can edit the saved filter you created and check the "include closed results" box. This should make the query exclude the invalid section that is causing the error.

Second, you can setup statuses. If you don't have any setup, you should setup a default one first ("New" or "Open" for example). Then setup a second status that has the "closed" attribute checked. This should also make the query work properly. 

I'll look into fixing this for cases when there are not statuses; however, this may be a bug in Ransack (the gem we're using for search query generation). 

Let me know if this helps!

**Comment by jwilczek** [comment]
I greatly appreciated your quick response.  The second I'm back in the
office I'll double-check this.  I'm betting you're correct.

In addition, do you guys have any documentation regarding the workflow you
use?  I've read the documentation on github and it really just mentions a
couple flags.  Could you talk to the difference between Workflow flags and
stages?

Thank you!

Josh

**Comment by jwilczek** [comment]
Just realized that this is discussed further in the "Extending Scumblr"
section.  I'd still like to hear about the workflow you use (if you're
willing to share it, of course).

Josh

**Comment by ahoernecke** [comment]
Hey Josh, I'd be happy to discuss with you. Would you mind pinging me directly on gitter? (https://gitter.im/monkeysecurity). We can use that to exchange contact information and find some time to chat. Thanks!

**Comment by jwilczek** [comment]
Sure - I'll do that this evening.  Thank you!
