### ISSUE TITLE
delete all searches (clear/purge/drop rails db)

### ISSUE THREAD

**Issue by tDorosheff** [Netflix/Scumblr#65]
I have about 80+ searches and i need to delete them. I have tried opening the rails console and doing:

Scumblr@scumblr:~/Scumblr$ rails c
Loading development environment (Rails 4.0.9)
[1] pry(main)> Search.delete 100
  SQL (0.1ms)  DELETE FROM "searches" WHERE "searches"."id" = 100
=> 0
[2] pry(main)>

But then when i go into the searches tab in the web UI, i can see the search still there, i can run it and fetch results.

I know how i can use a for loop to programatically delete all the searches i want to delete, and the searches themselves are named 1, 2, 3, 4 ..... 100. However despite my efforts through the rails console i cant remove them from my database.

**Comment by ahoernecke** [comment]
Hi @tDorosheff,

You should be able to delete them from the console with:

Search.delete_all

Let me know if this helps.

**Comment by tDorosheff** [comment]
alright, tried that and i still see all of the searches in the web ui, however when i click any of them i cant run them. From the searches tab, i can see "edit" "destroy" next to each search. clicking edit, i still see info in the name and query field, but at the bottom of the edit page, i can only update search and go back.

**Comment by ahoernecke** [comment]
Any chance you have more than one database you're working with (development, production, etc.) and that you're in a different environment in the console than in the web ui? The console will default to development.

Can you post the results of the delete_all from the console, and afterwards also run:

Search.count

...just so we can see if it's actually deleting them or not?

**Comment by tDorosheff** [comment]
[2] pry(main)* Search.delete_all
[2] pry(main)*

[2] pry(main)* Search.count
[2] pry(main)*

**Comment by tDorosheff** [comment]
okay now i reloaded the console and ran it again and this is what i got:

[2] pry(main)> Search.delete_all
  SQL (9.1ms)  DELETE FROM "searches"
=> 0
[3] pry(main)> Search.count
   (0.2ms)  SELECT COUNT(*) FROM "searches"
=> 0

**Comment by tDorosheff** [comment]
okay i restarted Scumblr and now im seeing no searches in the search tab, guess i just had to reload the app

**Comment by ahoernecke** [comment]
Very strange, I'm not sure what could have caused that behavior.
