### ISSUE TITLE
cant figure out proper syntax for search options 

### ISSUE THREAD

**Issue by tDorosheff** [Netflix/Scumblr#66]
Back at it again today, trying to build my 100+ searches using my for loop. Would like to set the "max results age(days)" to 1 day for my searches. I did a "Search.last" and took a look at the result to get an idea of the proper naming for the options, and then came up with the following attempt:

Search.create(name: "test", description: "test", query: "test", provider: "SearchProvider::Google", options: cx=>"", site=>"", days_to_search=>"1")

But that didnt work.

So far i have tried a couple different syntaxes, but each time im getting a syntax error. I figured that the proper syntax would be:

Search.create(name: "test4", description: "test", query: "test", provider: "SearchProvider::Google", options: cx::"", site::"", days_to_search::"1")

But that too did not work.

Could you please show me what im doing wrong? Thanks

**Comment by ahoernecke** [comment]
Hey @tDorosheff,

Looks like you were close; I think you just need a couple syntax adjustments. Try something like this:

```
Search.create(name: "test4", description: "test", query: "test", provider: "SearchProvider::Google", options: {cx:"", site:"", days_to_search:"1"})
```

**Comment by tDorosheff** [comment]
that worked. Hopefully this will conclude my need for further advice, but, until next time.

-Ted

**Comment by ahoernecke** [comment]
Good to hear, glad I could help!
