### ISSUE TITLE
Screenshots not generating automatically

### ISSUE THREAD

**Issue by mrjayway** [Netflix/Scumblr#67]
Hi,

Fantastic application. Unfortunately I am having difficulty getting Scumblr to generate screenshots for all results automatically.

Everything works fine when I click generate on the thumbnail, but I was hoping for the screenshot to be generated automatically as soon as the search results arrive. Is this possible?

Cheers.

**Comment by ahoernecke** [comment]
Hello @mrjayway,

You can have screenshots generated automatically, but you'll need to setup a cron job to run a rake task. 

You can either have the cron job run:

```
rake generate_screenshots
```
or... 

```
rake sync_all
```

The first will find all results without screenshots and request them. The first will run all the searches first and then request screenshots for results without them.

**Comment by mrjayway** [comment]
Excellent. Thank you!
