### ISSUE TITLE
bundle install giving problems

### ISSUE THREAD

**Issue by xsallowed** [Netflix/Scumblr#68]
I am getting following error

An error occurred while installing nokogiri (1.5.11), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.5.11'` succeeds before bundling.

while running bundle install

Regards

**Comment by ahoernecke** [comment]
Hello,

I'm not sure I can help without more information. Are you following the instructions from the wiki? Have you installed all the dependencies listed? Are you on Ubuntu or another operating system? What version of ruby are you using? Can you please post the full output from your bundle install command?

Thanks!

**Comment by xsallowed** [comment]
Hello I am on ubuntu 14.04 LTS Desktop and using main repo as source list. I am using it on server now but getting broken dependencies. Is there any distro available for your software code.Best Tahir  

    On Sunday, 24 January 2016, 20:35, Andy Hoernecke <notifications@github.com> wrote:
 

 Hello,I'm not sure I can help without more information. Are you following the instructions from the wiki? Have you installed all the dependencies listed? Are you on Ubuntu or another operating system? What version of ruby are you using? Can you please post the full output from your bundle install command?Thanks!—

**Comment by ahoernecke** [comment]
Hi Tahir,

There is a docker distribution available here: https://github.com/ahoernecke/docker_scumblr 

However, it's not currently officially maintained or supported. If you have issues with that, please make sure you're following the directions from the wiki when installing from source. https://github.com/Netflix/Scumblr/wiki

Thanks!
