### ISSUE TITLE
Unable to send email

### ISSUE THREAD

**Issue by benjimons** [Netflix/Scumblr#71]
Hey Guys,

I have a problem where no new results will send an email out as the notification. I have set up the filter search and results do show up when using it in the WebUI however no new results are sent out via email

I have the following configured in my development.rb file:

  config.action_mailer.raise_delivery_errors = false
  config.action_mailer.default_url_options = { :host => "localhost:3000", :protocol => 'http' }
  config.action_mailer.default_options = {from: 'scumblr@mydomain.co.nz'}
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
  address:              '127.0.0.1',
  port:                 25,
  domain:               'mydomain.co.nz'
  }

And if i run 
$ rake send_email_updates
(in /home/user/Scumblr)

It ends in what looks like success however no mail is ever attempted to be sent, there is no errors in either development log or sidekiq log.

**Comment by ahoernecke** [comment]
Hi @benjimons,

Have you subscribed to a saved filter? Probably too obvious, but do you have an smtp server running on localhost?

**Comment by benjimons** [comment]
Yeah I have saved a filter and have postfix running as my smtp server which
I can confirm works using sendmail

**Comment by ahoernecke** [comment]
Sorry, just want to be clear here. Did you *subscribe* to the saved filter you created--meaning, did you add your email address to the subscribers field when you created/edited the saved filter?

**Comment by benjimons** [comment]
Oh yeah I subscribed to it :)

**Comment by ahoernecke** [comment]
Are you running scumblr in a development mode? If you, so you may need to add this line to your config/environments/development.rb file:
```
config.action_mailer.perform_deliveries = true
```

If you've run the send_email_updates task, rerunning it will only results that are new since the last time the task was run. You can reset this by going into the console: 

```
rails c
``` 

and running this command:

```
Summary.delete_all
```


Try this and check your postfix log (Possibly /var/log/mail.log) and see if you're seeing any messages in there.

**Comment by benjimons** [comment]
Got it going, appears that the rails was rejecting the ssl cert, disabled that using the following
http://batsov.com/articles/2012/12/06/dealing-with-ssl-certificate-validation-errors-in-rails/

**Comment by ahoernecke** [comment]
Awesome, glad to hear you got it working!
