### ISSUE TITLE
Still getting SSL Error

### ISSUE THREAD

**Issue by sylcvqnr** [Netflix/Scumblr#77]
I saw some issues but none of them commented how it was solved. Can anyone help me ?
```ERROR: SSL_connect returned=1 errno=0 state=error: certificateficate verify failed```

**Comment by ahoernecke** [comment]
Hi @sylcvqnr, where exactly are you seeing this error?

**Comment by sylcvqnr** [comment]
In my sidekiq.log. I tried to search through twitter but I don't receive any search results and the scumblr.rb file already have the API keys

**Comment by ahoernecke** [comment]
Does your connection traverse through a proxy? The error would seem to indicate it's not able to verify Twitter's ssl certificate. I have seen that with systems that are not using valid certs, but not sure why you'd be seeing that with twitter...

**Comment by ahoernecke** [comment]
Any progress on this?

**Comment by sbehrens** [comment]
Closed due to 2.0 Scumblr release, if this is still needed please reopen this ticket.
