### ISSUE TITLE
Search Provider options never display their 'description', only their name

### ISSUE THREAD

**Issue by mig5** [Netflix/Scumblr#80]
I noticed that the 'description' attribute of a Search Provider's 'option', is never actually displayed anywhere.

The app/views/providers/_options_fields.html.erb is purely a form, so can only display labels and input fields (or hidden fields).

Is there a way to display this in some way? Case in point, pull request https://github.com/Netflix/Scumblr/pull/40 where I have to explain an option's valid values, in the 'name', so that the user receives visual indication on what to do.

I modified the builder.label in app/views/providers/_options_fields.html.erb to be something like this:

```
<%= builder.label value[:name] + (value[:description].to_s != '' ? " (" + value[:description].to_s + " )" ? "") +  (value[:required] == true ? "*" : "") %><br/>
```
but it's a bit ugly, and moreover, a lot of the search providers options *names* are almost verbatim equivalent to the description, so then you'd get a long doubled-up line of words, unless you stripped back either some of the names/descriptions so it's more coherent.

Overall, it would be useful if we could somehow inject a small print 'helper' beneath the label (or javascript/hover text?) that outputs the description.

Hope I am making sense :) I'm not a Ruby dev so not sure if there is a smart way of doing it.

**Comment by ahoernecke** [comment]
Hey @mig5, 

I have implemented this as a tooltip/hint icon in an upcoming version. I think the change was minor and I'll see if I can get it merged in here.

**Comment by ahoernecke** [comment]
Just merged in, should be working now.
