### ISSUE TITLE
Unable to access data from port 3000 on AWS VM

### ISSUE THREAD

**Issue by gabbifish** [Netflix/Scumblr#83]
I deployed Scumblr on an AWS VM running Ubuntu 14.04.3, and have followed the setup instructions through setting up the admin user and running Scumblr for the first time. but when we try to load the browser view of Scumblr via aws.ip.address.here:3000, we get a connection timeout. Any idea why this may be happening? I have also curl-ed the data from aws.ip.address.here:3000 and download no bytes from this curl attempt.

Thanks!

**Comment by ahoernecke** [comment]
Hi @gabbifish, have you tried SSHing into the AWS VM and running the curl command from the instance? If you're able to access from the instance I would suspect that the AWS security groups are not configured to allow access to port 3000 from where ever you are testing.

**Comment by oogali** [comment]
Adding onto @ahoernecke's comment, please log in to your AWS instance and try running ```curl http://localhost:3000```. If that works, then yes, it's likely an AWS security group issue (e.g. TCP/3000 not explicitly allowed)

**Comment by ahoernecke** [comment]
Thanks @oogali. Since there hasn't been a response from the OP I'm going to close this issue. @gabbifish if you're still having the issue please feel free to reopen with more details.
