### ISSUE TITLE
Fresh installs since the 19th throw lots of errors

### ISSUE THREAD

**Issue by mig5** [Netflix/Scumblr#84]
Did a fresh install of Scumblr in a fresh Vagrant VM. Getting errors trying to add a new Search:

```
NoMethodError in SearchesController#new

undefined method `first' for nil:NilClass
```

See screenshot.

Also got similar errors on an existing install after doing a git pull and running those recent rake db migrations, when trying to edit or run existing searches.

Might be time to move to a more formal 'tagged release' approach for Scumblr, since new features appear to be getting added (and presumably that's what's caused the breakage here in recent days)?

<img width="1270" alt="screen shot 2016-04-20 at 4 05 34 pm" src="https://cloud.githubusercontent.com/assets/99173/14664872/0c111d60-0712-11e6-87ef-72a57a354fc8.png">

**Comment by ahoernecke** [comment]
Hi @mig5,

Yes I totally agree. To explain what's going on, we've made some pretty big changes internally that will require some users to make some changes to their environment when we release the updates to open source (if they want the new features). We're working on getting all the bugs worked out of the new release and making sure we can provide an upgrade path that is as smooth as possible.

Meanwhile, I had been trying to port some of the features that don't require the environment changes back to the current version for existing users. It looks like I introduced a couple bugs when I did that, definitely sorry about that. At this point I'm really only adding bug fixes into the public repo until the new version is ready. When we do release the big update I will try to move to a more formalized release approach.

I just pushed an update that addresses the bug you identified as well as a couple others. I ran through some testing and things seemed to be working ok. If you identify and other bugs please let me know. Sorry again for the inconvenience.

**Comment by mig5** [comment]
Thanks @ahoernecke, makes sense :) things are working fine now since your bug fix too thanks. Sorry if it created extra work e.g the necessary fixes being irrelevant by the upcoming changes.

Definitely will be worth a tagged release (perhaps as things stand now, or even at the last commit from a few days ago) and then another when the new changes come in, in case users want to switch between. And hopefully a blog post or something to explain the new features :)

Happy to do any future (manual) testing for regressions if desired.

A side question, do you know if there's a sane way to automate the new user creation instead of via rails c? Even an optional rake command to do it? Would love to automate end-to-end the installation process, for testing/development. Vagrant script works almost perfectly for that otherwise.

**Comment by ahoernecke** [comment]
No worries, would much rather have the bugs ironed out! Will definitely put out information on the new features either via blog post or some other means.

As to your other question, there are a lot of ways to automate user creation. As an example, the unofficial scumblr docker container uses seeds to create an admin user:

https://github.com/ahoernecke/docker_scumblr/blob/master/config/scumblr/seeds.rb

That file would go in the db directory and then you'd just need to run the db:seed task to have them loaded:

`bundle exec rake db:seed `

**Comment by mig5** [comment]
Thanks!

**Comment by gabbifish** [comment]
Which commit represents the last stable release? Would love to use that version in the meantime!

**Comment by ahoernecke** [comment]
@gabbifish, you should probably pull the latest from master.
