### ISSUE TITLE
Navigation is wrapped on 13" laptop monitor

### ISSUE THREAD

**Issue by mig5** [Netflix/Scumblr#85]
Again, if this is something likely to be made obsolete by your upcoming changes, feel free to just close this.

After creating a fresh development environment with admin account 'admin@admin.admin' I noticed that the Navigation wraps on a standard Macbook Pro 13" screen. I think this is new for me for 2 reasons:

1) my real email address in a production Scumblr is shorter than admin@admin.admin
2) new extra navigation options 'Events' and 'Event Filters' and 'Result Filters'

<img width="1275" alt="screen shot 2016-04-22 at 9 10 21 am" src="https://cloud.githubusercontent.com/assets/99173/14727035/76b3a1f2-086a-11e6-8206-3797544cdf8a.png">

Maybe instead of displaying the user's email address, that nav item could simply be hardcoded to 'Profile' or something?

**Comment by mig5** [comment]
Either that or the assets/scumblr_logo.png could conceivably be shrunk down a bit, there is a wide gray region to the right of 'Scumblr' that causes Dashboard (and hence all other nav items) to appear at such a distance from the logo.

**Comment by ahoernecke** [comment]
Just pushed an update that should help with this... Reduced the spacing a little, collapsed the logout button to be under a dropdown on the user's email address, and truncate the email address to 20 characters max. Additionally, if the window is less than 1250px wide it puts the menu items inside a hamburger button. 

Take a look and let me know what you think.

**Comment by mig5** [comment]
That's really nice, a great improvement. Thanks!
