### ISSUE TITLE
Login issue 'Couldn't find User with id=undefined'

### ISSUE THREAD

**Issue by mig5** [Netflix/Scumblr#86]
At some point in my recent Vagrant testing, I have been getting the attached error after submitting the login form (with correct credentials only).

<img width="1088" alt="screen shot 2016-04-22 at 9 38 39 am" src="https://cloud.githubusercontent.com/assets/99173/14727684/afb6287a-0870-11e6-9085-f6561a81fdab.png">

If I take out the route from the URL in the exception above, I find I am actually logged in fine, same if I substitute with /searches, everything is OK. It's just the routing from after POSTing the form that throws it.

I edited the line in users_controller.rb in question, to resemble similar entries in results_controller.rb:

```
@user = current_user.try(:admin) && params[:user_id].present? ? User.find_by_id(params[:user_id]) : current_user
```

After that, I no longer get the error on login. I am taken to my user profile page, however, the route is /users/undefined but this at least doesn't seem as fatal (or is simply ignored as not understood).

<img width="1072" alt="screen shot 2016-04-22 at 9 59 07 am" src="https://cloud.githubusercontent.com/assets/99173/14727699/e1bdd2c8-0870-11e6-95de-f476caa702b6.png">

Not sure how/when this issue was introduced? Can you reproduce?

**Comment by ahoernecke** [comment]
Hey @mig5,

Trying to reproduce this but I haven't been able to. Can you post some additional info? 

-Specifically if you could post your rails log 
-The details of the user you're trying to login as:
```
User.first.inspect
# or
User.find( id ).inspect
```
-If you could get something like a network log from your browser's debug console that could be useful to.

It seems like, for some reason it's redirecting you to /users/undefined (instead of /users/<id>). Your debug page appear to the id parameter is set to "undefined" for some reason... not sure what would be causing that.

**Comment by mig5** [comment]
Hi @ahoernecke ,

Here's the relevant bits from the development.log: https://gist.github.com/mig5/b426765a538468e2348ab2dcce18c546

```
vagrant@vagrant-ubuntu-precise-64:/vagrant/Scumblr$ rails c
User.first.inspecLoading development environment (Rails 4.0.9)
[1] pry(main)> User.first.inspect
  User Load (1.6ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT 1
=> "#<User id: 1, email: \"admin@admin.admin\", encrypted_password: \"$2a$10$uhp6Z7oHpSknMQMB548th.ZNi78t0r/OaPPNxrVNfWKG...\", sign_in_count: 1, current_sign_in_at: \"2016-04-26 01:38:33\", last_sign_in_at: \"2016-04-26 01:38:33\", current_sign_in_ip: \"10.0.2.2\", last_sign_in_ip: \"10.0.2.2\", created_at: \"2016-04-26 01:38:09\", updated_at: \"2016-04-26 01:38:33\", provider: nil, uid: nil, admin: true, disabled: nil>"
[2] pry(main)> user.find( id ).inspect
NameError: undefined local variable or method `user' for main:Object
```

So interesting, I couldn't reproduce this in Chrome, only in Firefox 45.0.2 on OS X. It is probably going to be something to do with an Add-on/plugin. I'll continue to debug but you can probably close this. Sorry for the distraction.

**Comment by ahoernecke** [comment]
Sounds good, let me know if you find an issue that needs to be addressed.
