### ISSUE TITLE
Ruby 2.0.0-p481 Install issue

### ISSUE THREAD

**Issue by geekrepublic** [Netflix/Scumblr#87]
When doing the following command I get 
rbenv install 2.0.0-p481

**Installing ruby-2.0.0-p481...

WARNING: ruby-2.0.0-p481 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.**

How can I get around this. It just sits there.

**Comment by ahoernecke** [comment]
Hello @geekrepublic, have you tried installing a newer version of ruby? Should work fine on a 2.1/2.2 version as well.

**Comment by oogali** [comment]
That message is merely a warning, not a fatal error message.

And it's not just sitting there, it's just compiling 2.0.0-p481... really slowly. Give it some time.
