### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by cantino** [Netflix/Scumblr#89]
Adding screenshots to the README or wiki would be useful for providing potential new users with insight into the application and what it can do.

**Comment by ahoernecke** [comment]
Thanks @cantino, I'll keep this in mind for the next round of updates to the documentation.

**Comment by sbehrens** [comment]
Closed due to 2.0 Scumblr release (Wiki is much improved), if this is still needed please reopen this ticket or hop in the Scumblr Gitter chat room.
