### ISSUE TITLE
Documentation Request: API keys

### ISSUE THREAD

**Issue by jessekrembs** [Netflix/Scumblr#9]
It would be really great if there was a quick guide that helped explain how/where to get the apprioate keys for each of the various search applications. For example right now I'm swimming around in google's dev land trying to figure out cx and application names.
Also I'm pretty sure I have the Facebook keys set-up but for some reason the search doesn't work.

**Comment by sbehrens** [comment]
Closed due to 2.0 release, if this is still a problem please reopen this issue.
