### ISSUE TITLE
Scumblr Email notifications not working 

### ISSUE THREAD

**Issue by enasda** [Netflix/Scumblr#92]
I performed searches which has results related to a saved filter, and I added my email in subscribers but I don't receive email notification. 
I am beginner in this so I haven't made any configurations for mail except the following:

> nano Scumblr/config/environments/production.rb

_

> config.action_mailer.delivery_method = :smtp
   config.action_mailer.smtp_settings = {
   address: 'smtp.gmail.com',
   port: 587,
   user_name: 'myemail@gmail.com',
   password: 'email password',
   authentication: 'plain',
   enable_starttls_auto: true }

  # 

> Disable delivery errors, bad email addresses will be ignored
>    config.action_mailer.raise_delivery_errors = true
>    config.action_mailer.perform_deliveries = true
>    config.action_mailer.default_url_options = { :host => "localhost:3000", :protocol => 'https' }
>    config.action_mailer.default_options = {from: 'no reply@scumblr.com'}
>

**Comment by ahoernecke** [comment]
Did you also run the rake task to send out notifications? Are you sure you're running your application (and the rake task for that matter) in the production environment (default would be development).

**Comment by enasda** [comment]
I tried both `rake sync all` and `rake send_email_updates` none of them worked but no I didn't change the environment from the default.

**Comment by ahoernecke** [comment]
So I would try applying the config updates to config/environments/development.rb. Then run rake tasks:

```
RAILS_ENV=development rake sync_all
RAILS_ENV=development rake send_email_updates
```

Your searches will need to find new results of course. Try the above and let me know what the output looks like.

**Comment by enasda** [comment]
I tried it and received an email with the results

**Comment by ahoernecke** [comment]
Good, glad it's working.
