### ISSUE TITLE
Code is starting to get a little rusty

### ISSUE THREAD

**Issue by MadBomber** [Netflix/Scumblr#97]
The code base is starting to get a little rusty ...
```bash
git clone ... Scumblr
cd Scumblr
bundle install
rake db:create
ruby-2.3.1 Git:master Scumblr $ rake db:schema:load
rake aborted!
LoadError: cannot load such file -- google/api_client
/Users/dvanhoozer/.rvm/gems/ruby-2.3.1/gems/activesupport-4.0.9/lib/active_support/dependencies.rb:229:in `require'
```

**Comment by ahoernecke** [comment]
Hi @MadBomber,

Are you operating off the latest code on master? I just did a fresh clone, bundle install, etc. and couldn't reproduce this error. Can you repost your full shell history? It looks like the formatting or something was messed up in your initial comment.

**Comment by MadBomber** [comment]
it was a fresh clone of the master repo.  I've forked the project and
started an upgrade branch.  So far the principle difference in my setup is
Ruby version 2.3.1.  In mt branch I was able to get the project working
simply by commenting our the "require 'rubygems'" and "require
'google/api_client'" lines in all the places they appeared.

I have not poked by creds into the initializers yet - so I have not done a
full round trip on the code.

I also ran into a CSS/SCSS problem that was causing a syntax error message
to be shown.  The location given in the syntax error message is bogus.  I
have only tracked in down as far as somewhere in the foundation system.

On Fri, Jul 8, 2016 at 10:46 AM, Andy Hoernecke <notifications@github.com>
wrote:

> Hi @MadBomber <https://github.com/MadBomber>,
>
> Are you operating off the latest code on master? I just did a fresh clone,
> bundle install, etc. and couldn't reproduce this error. Can you repost your
> full shell history? It looks like the formatting or something was messed up
> in your initial comment.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Netflix/Scumblr/issues/97#issuecomment-231395538>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AABSbWm3afU4DkYav2WLm5afk7JSX4kxks5qTnDpgaJpZM4JHosC>
> .
>



-- 
Dewayne
  o-*

**Comment by ahoernecke** [comment]
Got it, yeah there are definitely some compatibility issues with Ruby 2.3 and it's not supported for the current version. Please the wiki for installation instructions. If you're not able to get it working with those instructions and the specified requirements, please open another issue.

Thanks!
