### ISSUE TITLE
Cannot create admin user

### ISSUE THREAD

**Issue by Subbax** [Netflix/Scumblr#98]
Hi,

Apologies in advance if I've missed something obvious!  I've been following the wiki guide to getting Scumblr on Ubuntu 14.04 and can get each step done up to Create an Admin User.  The error I'm getting is:

~/Scumblr$ ../.rbenv/versions/2.0.0-p481/bin/rails c
-bash: ../.rbenv/versions/2.0.0-p481/bin/rails: No such file or directory

Sure enough, /home/user/.rbenv/versions/2.0.0-p481/bin doesn't have a rails file.  I do however have a rails file in /home/user/Scumblr/bin.  I'm surprised as Rails was installed before Scumblr and running rails -v shows Rails 4.0.9

What am I doing wrong?
Thanks!

**Comment by ahoernecke** [comment]
Hey @subbax,

It looks like some changes were made to the wiki that aren't entirely accurate. Can you do the following:

1. Make sure your rbenv shims folder is in your PATH? (It's probably ~/.rbenv/shims)
2. From the directory where you installed scumblr run:
```
bundle exec rails c
```

See if that helps

**Comment by Subbax** [comment]
Hi @ahoernecke,

That worked like a charm!

Thanks so much for the quick response.  I'm up and running now.
